{-# LANGUAGE OverloadedStrings #-}

module Site.Content.Compiler.Emit
  ( emitPosts
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.IO as TIO
import Language.Haskell.TH (Exp (..), Lit (..), Name, mkName)
import Language.Haskell.TH.Ppr (ppr)
import Language.Haskell.TH.PprLib (to_HPJ_Doc)
import Text.PrettyPrint.HughesPJ (render)
import Site.Content.Types (Post (..), PublicationStatus (..), TocEntry (..))
import Site.Prose.Types (Block (..), ColumnAlignment (..), Footnote (..), Inline (..))
import Site.Section (Section (..))
import System.Directory (createDirectoryIfMissing, doesFileExist)
import System.FilePath (takeDirectory)

emitPosts :: FilePath -> [Post] -> IO ()
emitPosts path posts = do
  createDirectoryIfMissing True (takeDirectory path)
  let output = renderModule posts
  exists <- doesFileExist path
  unchanged <- if exists then (== output) <$> TIO.readFile path else pure False
  if unchanged
    then pure ()
    else TIO.writeFile path output

renderModule :: [Post] -> Text
renderModule posts = T.pack $ unlines
  [ "-- This file is generated by content-compiler."
  , "-- Do not edit by hand; run `make content` instead."
  , "{-# LANGUAGE OverloadedStrings #-}"
  , "module Site.Content.Generated (posts) where"
  , ""
  , "import Site.Content.Types (Post (..), TocEntry (..), PublicationStatus (..))"
  , "import Site.Section (Section (..))"
  , "import Site.Prose.Types (Block (..), ColumnAlignment (..), Footnote (..), Inline (..))"
  , ""
  , "posts :: [Post]"
  , "posts ="
  , "  [ " <> commaList (map bindingName [0 .. length posts - 1]) <> " ]"
  , ""
  ] <> T.unpack (T.concat (zipWith renderPost [0 ..] posts))
  where
    bindingName index = "post" <> show index
    commaList = joinWith ", "

renderPost :: Int -> Post -> Text
renderPost index post = T.pack $ unlines
  [ binding <> " :: Post"
  , binding <> " ="
  , "  " <> renderExp (postExp post)
  , ""
  ]
  where
    binding = "post" <> show index

postExp :: Post -> Exp
postExp post = RecConE (name "Post")
  [ (name "postTitle", textExp (postTitle post))
  , (name "postDate", textExp (postDate post))
  , (name "postDateLabel", textExp (postDateLabel post))
  , (name "postSlug", textExp (postSlug post))
  , (name "postSection", sectionExp (postSection post))
  , (name "postStatus", statusExp (postStatus post))
  , (name "postTags", listExp (map textExp (postTags post)))
  , (name "postExcerpt", textExp (postExcerpt post))
  , (name "postBanner", textExp (postBanner post))
  , (name "postOgTitle", textExp (postOgTitle post))
  , (name "postOgDescription", textExp (postOgDescription post))
  , (name "postOgImage", textExp (postOgImage post))
  , (name "postBody", listExp (map blockExp (postBody post)))
  , (name "postToc", listExp (map tocExp (postToc post)))
  ]

blockExp :: Block -> Exp
blockExp block = case block of
  Paragraph inlines -> app "Paragraph" [listExp (map inlineExp inlines)]
  Plain inlines -> app "Plain" [listExp (map inlineExp inlines)]
  Heading level anchor inlines -> app "Heading" [intExp level, textExp anchor, listExp (map inlineExp inlines)]
  CodeBlock language inlines -> app "CodeBlock" [maybeExp textExp language, listExp (map inlineExp inlines)]
  BulletList items -> app "BulletList" [listExp (map (listExp . map blockExp) items)]
  OrderedList start items -> app "OrderedList" [intExp start, listExp (map (listExp . map blockExp) items)]
  BlockQuote blocks -> app "BlockQuote" [listExp (map blockExp blocks)]
  Table alignments header body -> app "Table"
    [ listExp (map alignmentExp alignments)
    , listExp (map (listExp . map (listExp . map inlineExp)) header)
    , listExp (map (listExp . map (listExp . map inlineExp)) body)
    ]
  Rule -> nameExp "Rule"
  Footnotes footnotes -> app "Footnotes" [listExp (map footnoteExp footnotes)]

inlineExp :: Inline -> Exp
inlineExp inline = case inline of
  Text value -> app "Text" [textExp value]
  Emphasis values -> app "Emphasis" [listExp (map inlineExp values)]
  Strong values -> app "Strong" [listExp (map inlineExp values)]
  Code value -> app "Code" [textExp value]
  Link href title values -> app "Link" [textExp href, maybeExp textExp title, listExp (map inlineExp values)]
  Image source alt title -> app "Image" [textExp source, textExp alt, maybeExp textExp title]
  PlainImage source alt title -> app "PlainImage" [textExp source, textExp alt, maybeExp textExp title]
  Video source alt title -> app "Video" [textExp source, textExp alt, maybeExp textExp title]
  SoftBreak -> nameExp "SoftBreak"
  HardBreak -> nameExp "HardBreak"
  FootnoteRef number refId -> app "FootnoteRef" [intExp number, textExp refId]
  Span className values -> app "Span" [textExp className, listExp (map inlineExp values)]

footnoteExp :: Footnote -> Exp
footnoteExp footnote = RecConE (name "Footnote")
  [ (name "footnoteNumber", intExp (footnoteNumber footnote))
  , (name "footnoteRefs", listExp (map textExp (footnoteRefs footnote)))
  , (name "footnoteBlocks", listExp (map blockExp (footnoteBlocks footnote)))
  ]

tocExp :: TocEntry -> Exp
tocExp entry = RecConE (name "TocEntry")
  [ (name "tocId", textExp (tocId entry))
  , (name "tocLabel", textExp (tocLabel entry))
  , (name "tocLevel", intExp (tocLevel entry))
  ]

sectionExp :: Section -> Exp
sectionExp Thought = nameExp "Thought"
sectionExp Lab = nameExp "Lab"

statusExp :: PublicationStatus -> Exp
statusExp Draft = nameExp "Draft"
statusExp Published = nameExp "Published"

alignmentExp :: ColumnAlignment -> Exp
alignmentExp AlignLeft = nameExp "AlignLeft"
alignmentExp AlignCenter = nameExp "AlignCenter"
alignmentExp AlignRight = nameExp "AlignRight"
alignmentExp AlignDefault = nameExp "AlignDefault"

textExp :: Text -> Exp
textExp = LitE . StringL . T.unpack

intExp :: Int -> Exp
intExp = LitE . IntegerL . fromIntegral

maybeExp :: (a -> Exp) -> Maybe a -> Exp
maybeExp _ Nothing = nameExp "Nothing"
maybeExp renderValue (Just value) = app "Just" [renderValue value]

listExp :: [Exp] -> Exp
listExp = ListE

nameExp :: String -> Exp
nameExp = ConE . name

app :: String -> [Exp] -> Exp
app constructor = foldl AppE (nameExp constructor)

name :: String -> Name
name = mkName

renderExp :: Exp -> String
renderExp = render . to_HPJ_Doc . ppr

joinWith :: String -> [String] -> String
joinWith _ [] = ""
joinWith _ [value] = value
joinWith separator (value : rest) = value <> separator <> joinWith separator rest
