dust:
  openBrowser: false
  syntaxThemeUrl: "src/utils/monochrome-dark.json"

collections:
  blog:
    layout: layout_blog
    source: src/posts/articles
  # projects:
  #   layout: layout_blog
  #   source: src/posts/projects