packages:
  - '.'

allowBuilds:
  cpu-features: false
  esbuild: true
  msgpackr-extract: false
  purescript: true
  ssh2: false

minimumReleaseAgeExclude:
  - foldkit@0.153.0
  - '@foldkit/devtools-mcp@0.19.0'
  - '@foldkit/devtools@0.153.0'
  - '@foldkit/oxlint-plugin@0.9.0'
  - '@foldkit/vite-plugin@0.19.0'
  - '@foldkit/ui@0.153.0'
