-----------------------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards   #-}
-----------------------------------------------------------------------------
-- | The header's hollow mark, ported from the source's @HollowMark.purs@ and
-- @HollowMark.ts@. WebGL1, one instance, drag to spin.
--
-- The pure reference mesh is generated by 'Site.HollowGeometry'; a build step
-- emits the same mesh as milli-unit text for the browser. It is decoded into a
-- @Float32Array@ through one JavaScript helper call, then uploaded once. The
-- moon texture loads asynchronously and is re-uploaded on load.
module Site.Widgets.Hollow
  ( attach
  , dispose
  ) where
-----------------------------------------------------------------------------
import           Control.Monad (forM_, unless, void, when)
import           Data.Maybe (isJust)
import           Data.IORef
  ( IORef
  , modifyIORef'
  , newIORef
  , readIORef
  , writeIORef
  )
import           Prelude hiding ((!!))
import           Miso.DSL
  ( JSVal
  , create
  , fromJSValUnchecked
  , jsg
  , jsgf
  , jsNull
  , new
  , setField
  , syncCallback1
  , (!)
  , (#)
  , (!!)
  )
import           Miso.String (MisoString)
import           System.IO.Unsafe (unsafePerformIO)
-----------------------------------------------------------------------------
import           Site.Canvas (rasterLayout, rasterCanvasHeight, rasterCanvasWidth)
import qualified Site.Config as Config
import           Site.Hollow
import           Site.HollowGeometry (hollowVertexCount)
import           Site.Platform (prefersReducedMotion)
import           Site.Widgets.Gl
import           Site.Widgets.HollowGeometry (hollowGeometryText)
import           Site.Widgets.Shaders (hollowMarkFragment, hollowMarkVertex)
-----------------------------------------------------------------------------
data Uniforms = Uniforms
  { uniformAngle     :: JSVal
  , uniformCubeAngle :: JSVal
  , uniformAspect    :: JSVal
  , uniformTime      :: JSVal
  , uniformLabHover  :: JSVal
  }
-----------------------------------------------------------------------------
data Listener = Listener
  { listenerTarget   :: JSVal
  , listenerType     :: MisoString
  , listenerCallback :: JSVal
  , listenerCapture  :: Bool
  }
-----------------------------------------------------------------------------
data HollowLive = HollowLive
  { hollowCanvas       :: JSVal
  , hollowGl           :: JSVal
  , hollowProgram      :: GlProgram
  , hollowBuffer       :: JSVal
  , hollowTexture      :: JSVal
  , hollowImage        :: JSVal
  , hollowVerticesAt   :: Int
  , hollowUniforms     :: Uniforms
  , hollowStartedAt    :: Double
  , hollowReduceMotion :: Bool
  , hollowState        :: IORef HollowState
  , hollowHover        :: IORef Double
  , hollowSize         :: IORef (Int, Int)
  , hollowVisible      :: IORef Bool
  , hollowIntersecting :: IORef Bool
  , hollowRunning      :: IORef Bool
  , hollowRafCallback  :: IORef JSVal
  , hollowRafHandle    :: IORef (Maybe Int)
  , hollowPrevious     :: IORef (Maybe HollowUniforms)
  , hollowListeners    :: IORef [Listener]
  , hollowObservers    :: IORef [JSVal]
  , hollowDisposed     :: IORef Bool
  }
-----------------------------------------------------------------------------
hollowRef :: IORef (Maybe HollowLive)
hollowRef = unsafePerformIO (newIORef Nothing)
{-# NOINLINE hollowRef #-}
-----------------------------------------------------------------------------
retryRef :: IORef Int
retryRef = unsafePerformIO (newIORef 0)
{-# NOINLINE retryRef #-}
-----------------------------------------------------------------------------
-- | The mesh as a compact build-generated milli-unit payload: each quantized
-- value has 0.001 precision, and the JavaScript side decodes it to floats in
-- one call. This avoids a runtime float formatter and the cost of evaluating
-- all trigonometry during page startup. 0.001 is far below what a 16-pixel
-- mark can show.
--
-- Built once, decoded by one JavaScript function call into a @Float32Array@;
-- passing 300k numbers across the FFI individually would be slower than the
-- rest of the mount combined.
-----------------------------------------------------------------------------
attach :: IO ()
attach = do
  current <- readIORef hollowRef
  case current of
    Just _  -> pure ()
    Nothing -> do
      document <- jsg "document"
      canvas <- document # "querySelector" $ Config.hollowMarkSelector
      absent <- isAbsent canvas
      unless absent (mount canvas)
-----------------------------------------------------------------------------
dispose :: IO ()
dispose = do
  current <- readIORef hollowRef
  case current of
    Nothing   -> pure ()
    Just live -> do
      writeIORef (hollowDisposed live) True
      stopLoop live
      listeners <- readIORef (hollowListeners live)
      forM_ (reverse listeners) $ \listener ->
        void $ listenerTarget listener # "removeEventListener" $
          ( listenerType listener
          , listenerCallback listener
          , listenerCapture listener
          )
      observers <- readIORef (hollowObservers live)
      forM_ observers $ \observer -> void $ observer # "disconnect" $ ()
      let gl = hollowGl live
      void $ gl # "deleteBuffer" $ [hollowBuffer live]
      void $ gl # "deleteTexture" $ [hollowTexture live]
      deleteProgram gl (hollowProgram live)
      releaseContext gl
      writeIORef hollowRef Nothing
-----------------------------------------------------------------------------
mount :: JSVal -> IO ()
mount canvas = do
  context <- createWebGlContext canvas
  case context of
    Nothing -> retryMount
    Just gl -> do
      built <- build canvas gl
      case built of
        Nothing -> releaseContext gl
        Just live -> do
          writeIORef retryRef 0
          writeIORef hollowRef (Just live)
-----------------------------------------------------------------------------
retryMount :: IO ()
retryMount = mountWithRetry retryRef (isJust <$> readIORef hollowRef) attach
-----------------------------------------------------------------------------
createWebGlContext :: JSVal -> IO (Maybe JSVal)
createWebGlContext canvas = do
  options <- create
  setField options "alpha" True
  setField options "antialias" True
  setField options "depth" True
  setField options "premultipliedAlpha" True
  context <- canvas # "getContext" $ ("webgl" :: MisoString, options)
  absent <- isAbsent context
  pure (if absent then Nothing else Just context)
-----------------------------------------------------------------------------
build :: JSVal -> JSVal -> IO (Maybe HollowLive)
build canvas gl =
  compileProgram gl hollowMarkVertex hollowMarkFragment "hollow-mark" >>>= \program ->
  createVertexBuffer gl program >>>= \buffer ->
  createMoonTexture gl program >>>= \texture ->
  Just <$> createLive canvas gl program buffer texture
-----------------------------------------------------------------------------
createVertexBuffer :: JSVal -> GlProgram -> IO (Maybe JSVal)
createVertexBuffer gl program = do
  buffer <- gl # "createBuffer" $ ()
  absent <- isAbsent buffer
  if absent
    then pure Nothing
    else do
      vertices <- geometryArray
      void $ gl # "useProgram" $ [glProgram program]
      void $ gl # "bindBuffer" $ (glArrayBuffer, buffer)
      void $ gl # "bufferData" $ (glArrayBuffer, vertices, glStaticDraw)
      position <- attribLocation gl program "a_position"
      surfaceNormal <- attribLocation gl program "a_normal"
      region <- attribLocation gl program "a_region"
      let stride = 7 * 4
      vertexAttribute gl position 3 stride 0
      vertexAttribute gl surfaceNormal 3 stride (3 * 4)
      vertexAttribute gl region 1 stride (6 * 4)
      void $ gl # "enable" $ [glDepthTest]
      void $ gl # "depthFunc" $ [glLequal]
      void $ gl # "disable" $ [glCullFace]
      pure (Just buffer)
-----------------------------------------------------------------------------
createMoonTexture :: JSVal -> GlProgram -> IO (Maybe JSVal)
createMoonTexture gl program = do
  texture <- gl # "createTexture" $ ()
  absent <- isAbsent texture
  if absent
    then pure Nothing
    else do
      void $ gl # "activeTexture" $ [glTexture2]
      void $ gl # "bindTexture" $ (glTexture2D, texture)
      void $ gl # "texParameteri" $ (glTexture2D, glTextureWrapS, glRepeat)
      void $ gl # "texParameteri" $ (glTexture2D, glTextureWrapT, glClampToEdge)
      void $ gl # "texParameteri" $ (glTexture2D, glTextureMinFilter, glLinear)
      void $ gl # "texParameteri" $ (glTexture2D, glTextureMagFilter, glLinear)
      white <- whitePixels
      texImage2DWith gl glTexture2D 0 glRgba 1 1 0 glRgba glUnsignedByte white
      moonUniform <- getUniformLocation gl (glProgram program) "u_moon_texture"
      void $ gl # "uniform1i" $ (moonUniform, 2 :: Int)
      pure (Just texture)
-----------------------------------------------------------------------------
attribLocation :: JSVal -> GlProgram -> MisoString -> IO Int
attribLocation gl program name = do
  value <- gl # "getAttribLocation" $ (glProgram program, name)
  fromJSValUnchecked value
-----------------------------------------------------------------------------
getUniformLocation :: JSVal -> JSVal -> MisoString -> IO JSVal
getUniformLocation gl program name = gl # "getUniformLocation" $ (program, name)
-----------------------------------------------------------------------------
vertexAttribute :: JSVal -> Int -> Int -> Int -> Int -> IO ()
vertexAttribute gl location size stride offset = do
  void $ gl # "enableVertexAttribArray" $ [location]
  void $ gl # "vertexAttribPointer" $
    (location, size, glFloat, False, stride, offset)
-----------------------------------------------------------------------------
-- | @new Float32Array@ from the packed geometry string.
geometryArray :: IO JSVal
geometryArray = do
  constructor <- jsgf "Function"
    ( "source, vertexCount" :: MisoString
    , "const bytes = atob(source); const out = new Float32Array(vertexCount * 7); let bit = 0; const readBits = width => { let value = 0; for (let offset = 0; offset < width; offset++) { value |= ((bytes.charCodeAt(bit >> 3) >> (bit & 7)) & 1) << offset; bit++; } return value; }; for (let vertex = 0; vertex < vertexCount; vertex++) { const base = vertex * 7; for (let field = 0; field < 6; field++) out[base + field] = (readBits(11) - 1024) / 1000; out[base + 6] = readBits(3); } return out;" :: MisoString
    )
  constructor # "call" $ (jsNull, hollowGeometryText, hollowVertexCount)
-----------------------------------------------------------------------------
whitePixels :: IO JSVal
whitePixels = do
  constructor <- jsgf "Function"
    ("return new Uint8Array([255, 255, 255, 255]);" :: MisoString)
  constructor # "call" $ [jsNull]
-----------------------------------------------------------------------------
createLive :: JSVal -> JSVal -> GlProgram -> JSVal -> JSVal -> IO HollowLive
createLive canvas gl program buffer texture = do
  uniformAngle <- getUniformLocation gl (glProgram program) "u_angle"
  uniformCubeAngle <- getUniformLocation gl (glProgram program) "u_cube_angle"
  uniformAspect <- getUniformLocation gl (glProgram program) "u_aspect"
  uniformTime <- getUniformLocation gl (glProgram program) "u_time"
  uniformLabHover <- getUniformLocation gl (glProgram program) "u_lab_hover"
  startedAt <- performanceNow
  reduceMotion <- prefersReducedMotion
  hover <- readLabHover canvas
  state <- newIORef (initialHollowState startedAt)
  hoverRef <- newIORef hover
  size <- newIORef (1, 1)
  visible <- newIORef False
  intersecting <- newIORef False
  running <- newIORef False
  rafCallback <- newIORef jsNull
  rafHandle <- newIORef Nothing
  previous <- newIORef Nothing
  listeners <- newIORef []
  observers <- newIORef []
  disposed <- newIORef False
  image <- new (jsg "Image") ()
  setField image "decoding" ("async" :: MisoString)
  let live = HollowLive
        { hollowCanvas = canvas
        , hollowGl = gl
        , hollowProgram = program
        , hollowBuffer = buffer
        , hollowTexture = texture
        , hollowImage = image
        , hollowVerticesAt = hollowVertexCount
        , hollowUniforms = Uniforms {..}
        , hollowStartedAt = startedAt
        , hollowReduceMotion = reduceMotion
        , hollowState = state
        , hollowHover = hoverRef
        , hollowSize = size
        , hollowVisible = visible
        , hollowIntersecting = intersecting
        , hollowRunning = running
        , hollowRafCallback = rafCallback
        , hollowRafHandle = rafHandle
        , hollowPrevious = previous
        , hollowListeners = listeners
        , hollowObservers = observers
        , hollowDisposed = disposed
        }
  callback <- syncCallback1 $ \timestamp -> tick live timestamp
  writeIORef rafCallback callback
  loadMoon live
  applyLayout live
  registerPointer live
  registerResize live
  registerTheme live
  registerHover live
  registerVisibility live
  pure live
-----------------------------------------------------------------------------
loadMoon :: HollowLive -> IO ()
loadMoon live = do
  callback <- syncCallback1 $ \_ -> do
    disposed <- readIORef (hollowDisposed live)
    unless disposed $ do
      let gl = hollowGl live
      -- Set the unpack flag only for the image upload. It must not surround
      -- the typed-array placeholder upload during context setup.
      void $ gl # "pixelStorei" $ (glUnpackFlipY, 1 :: Int)
      void $ gl # "activeTexture" $ [glTexture2]
      void $ gl # "bindTexture" $ (glTexture2D, hollowTexture live)
      void $ gl # "texImage2D" $
        (glTexture2D, 0 :: Int, glRgba, glRgba, glUnsignedByte, hollowImage live)
  void $ hollowImage live # "addEventListener" $
    ("load" :: MisoString, callback)
  setField (hollowImage live) "src"
    ("/assets/images/lroc-color-1k.webp" :: MisoString)
-----------------------------------------------------------------------------
-----------------------------------------------------------------------------
readLabHover :: JSVal -> IO Double
readLabHover canvas = do
  value <- canvas # "getAttribute" $ ("data-" <> Config.labInteractionKey)
  text <- fromJSValUnchecked value :: IO (Maybe MisoString)
  pure (if text == Just Config.labInteractionHovered then 1.0 else 0.0)
-----------------------------------------------------------------------------
applyLayout :: HollowLive -> IO ()
applyLayout live = do
  let canvas = hollowCanvas live
      gl = hollowGl live
  rect <- canvas # "getBoundingClientRect" $ ()
  width <- fromJSValUnchecked =<< rect ! "width"
  height <- fromJSValUnchecked =<< rect ! "height"
  when (width >= 1.0 && height >= 1.0) $ do
    window <- jsg "window"
    ratio <- fromJSValUnchecked =<< window ! "devicePixelRatio"
    let layout = rasterLayout width height ratio 1.0 6.0
    writeIORef (hollowSize live)
      (rasterCanvasWidth layout, rasterCanvasHeight layout)
    setField canvas "width" (rasterCanvasWidth layout)
    setField canvas "height" (rasterCanvasHeight layout)
    void $ gl # "viewport" $
      (0 :: Int, 0 :: Int, rasterCanvasWidth layout, rasterCanvasHeight layout)
    writeIORef (hollowPrevious live) Nothing
    startLoop live
-----------------------------------------------------------------------------
tick :: HollowLive -> JSVal -> IO ()
tick live rawTimestamp = do
  running <- readIORef (hollowRunning live)
  when running $ do
    timestamp <- fromJSValUnchecked rawTimestamp
    drawFrame live timestamp
    scheduleFrame live
-----------------------------------------------------------------------------
scheduleFrame :: HollowLive -> IO ()
scheduleFrame live = do
  callback <- readIORef (hollowRafCallback live)
  window <- jsg "window"
  handle <- window # "requestAnimationFrame" $ [callback]
  handleId <- fromJSValUnchecked handle
  writeIORef (hollowRafHandle live) (Just handleId)
-----------------------------------------------------------------------------
drawFrame :: HollowLive -> Double -> IO ()
drawFrame live timestamp = do
  state <- readIORef (hollowState live)
  hover <- readIORef (hollowHover live)
  (canvasWidth, canvasHeight) <- readIORef (hollowSize live)
  let input = HollowInput
        { hiTimestamp = timestamp
        , hiStartedAt = hollowStartedAt live
        , hiReduceMotion = hollowReduceMotion live
        , hiLabHoverTarget = hover
        , hiDragging = hsDragging state
        , hiCanvasWidth = canvasWidth
        , hiCanvasHeight = canvasHeight
        }
      (stepped, uniforms) = hollowFrame input state
  writeIORef (hollowState live) stepped
  previous <- readIORef (hollowPrevious live)
  when (previous /= Just uniforms) $ do
    drawUniforms live uniforms
    writeIORef (hollowPrevious live) (Just uniforms)
-----------------------------------------------------------------------------
drawUniforms :: HollowLive -> HollowUniforms -> IO ()
drawUniforms live uniforms = do
  let gl = hollowGl live
      Uniforms {..} = hollowUniforms live
  -- Keep the program association explicit. Resize/theme callbacks can run
  -- after another WebGL operation has changed the current program.
  void $ gl # "useProgram" $ [glProgram (hollowProgram live)]
  void $ gl # "clearColor" $ (0.0 :: Double, 0.0 :: Double, 0.0 :: Double, 0.0 :: Double)
  void $ gl # "clear" $ [glColorDepthBits]
  void $ gl # "uniform1f" $ (uniformAngle, huAngle uniforms)
  void $ gl # "uniform1f" $ (uniformCubeAngle, huCubeAngle uniforms)
  void $ gl # "uniform1f" $ (uniformAspect, huAspect uniforms)
  void $ gl # "uniform1f" $ (uniformTime, huTime uniforms)
  void $ gl # "uniform1f" $ (uniformLabHover, huLabHover uniforms)
  void $ gl # "drawArrays" $
    (glTriangles, 0 :: Int, hollowVerticesAt live)
-----------------------------------------------------------------------------
startLoop :: HollowLive -> IO ()
startLoop live = do
  running <- readIORef (hollowRunning live)
  visible <- readIORef (hollowVisible live)
  when (not running && visible) $ do
    writeIORef (hollowRunning live) True
    scheduleFrame live
-----------------------------------------------------------------------------
stopLoop :: HollowLive -> IO ()
stopLoop live = do
  writeIORef (hollowRunning live) False
  handle <- readIORef (hollowRafHandle live)
  forM_ handle $ \handleId -> do
    window <- jsg "window"
    void $ window # "cancelAnimationFrame" $ [handleId]
  writeIORef (hollowRafHandle live) Nothing
-----------------------------------------------------------------------------
addListener :: HollowLive -> JSVal -> MisoString -> Bool -> (JSVal -> IO ()) -> IO ()
addListener live target kind capture handler = do
  callback <- syncCallback1 handler
  void $ target # "addEventListener" $ (kind, callback, capture)
  modifyIORef' (hollowListeners live) (Listener target kind callback capture :)
-----------------------------------------------------------------------------
registerPointer :: HollowLive -> IO ()
registerPointer live = do
  let canvas = hollowCanvas live
  addListener live canvas "pointerdown" True $ \event -> do
    capturePointer canvas event
    handlePointer live HollowDown event
    markDragging live "true"
  addListener live canvas "pointermove" True (handlePointer live HollowMove)
  addListener live canvas "pointerup" True $ \event -> do
    handlePointer live HollowUp event
    markDragging live "false"
  addListener live canvas "pointercancel" True $ \event -> do
    handlePointer live HollowUp event
    markDragging live "false"
-----------------------------------------------------------------------------
capturePointer :: JSVal -> JSVal -> IO ()
capturePointer canvas event = do
  pointerId <- event ! "pointerId"
  void $ canvas # "setPointerCapture" $ [pointerId]
-----------------------------------------------------------------------------
markDragging :: HollowLive -> MisoString -> IO ()
markDragging live value =
  void $ hollowCanvas live # "setAttribute" $ ("data-" <> Config.hollowDraggingKey, value)
-----------------------------------------------------------------------------
handlePointer :: HollowLive -> HollowPointerKind -> JSVal -> IO ()
handlePointer live kind event = do
  void $ event # "preventDefault" $ ()
  let canvas = hollowCanvas live
  rect <- canvas # "getBoundingClientRect" $ ()
  width <- fromJSValUnchecked =<< rect ! "width"
  x <- fromJSValUnchecked =<< event ! "clientX"
  y <- fromJSValUnchecked =<< event ! "clientY"
  timestamp <- performanceNow
  state <- readIORef (hollowState live)
  writeIORef (hollowState live)
    (hollowPointer
      (HollowPointerEvent kind x y timestamp width)
      state)
  startLoop live
-----------------------------------------------------------------------------
registerResize :: HollowLive -> IO ()
registerResize live = do
  callback <- syncCallback1 $ \_ -> do
    applyLayout live
    when (hollowReduceMotion live) (renderNow live)
  observerClass <- jsg "ResizeObserver"
  observer <- new observerClass callback
  void $ observer # "observe" $ [hollowCanvas live]
  modifyIORef' (hollowObservers live) (observer :)
-----------------------------------------------------------------------------
registerTheme :: HollowLive -> IO ()
registerTheme live = do
  document <- jsg "document"
  element <- document ! "documentElement"
  callback <- syncCallback1 $ \_ -> renderNow live
  observerClass <- jsg "MutationObserver"
  options <- create
  setField options "attributes" True
  observer <- new observerClass callback
  void $ observer # "observe" $ (element, options)
  modifyIORef' (hollowObservers live) (observer :)
-----------------------------------------------------------------------------
registerHover :: HollowLive -> IO ()
registerHover live = do
  callback <- syncCallback1 $ \_ -> do
    value <- readLabHover (hollowCanvas live)
    writeIORef (hollowHover live) value
    startLoop live
  observerClass <- jsg "MutationObserver"
  options <- create
  setField options "attributes" True
  observer <- new observerClass callback
  void $ observer # "observe" $ (hollowCanvas live, options)
  modifyIORef' (hollowObservers live) (observer :)
-----------------------------------------------------------------------------
-- | The source gates the loop on intersection with a 120px margin and on tab
-- visibility; reduced-motion users get a single frame per change instead.
registerVisibility :: HollowLive -> IO ()
registerVisibility live = do
  options <- create
  setField options "rootMargin" ("120px" :: MisoString)
  observerClass <- jsg "IntersectionObserver"
  callback <- syncCallback1 $ \entries -> do
    first <- entries !! 0
    intersecting <- fromJSValUnchecked =<< first ! "isIntersecting"
    writeIORef (hollowIntersecting live) intersecting
    emitVisibility live
  observer <- new observerClass (callback, options)
  void $ observer # "observe" $ [hollowCanvas live]
  modifyIORef' (hollowObservers live) (observer :)
  document <- jsg "document"
  addListener live document "visibilitychange" False (\_ -> emitVisibility live)
-----------------------------------------------------------------------------
emitVisibility :: HollowLive -> IO ()
emitVisibility live = do
  intersecting <- readIORef (hollowIntersecting live)
  document <- jsg "document"
  visibility <- fromJSValUnchecked =<< document ! "visibilityState"
  let visible = intersecting && visibility == ("visible" :: MisoString)
  writeIORef (hollowVisible live) visible
  when visible (renderNow live)
  if visible then startLoop live else stopLoop live
-----------------------------------------------------------------------------
renderNow :: HollowLive -> IO ()
renderNow live = do
  timestamp <- performanceNow
  drawFrame live timestamp
