-----------------------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards   #-}
{-# LANGUAGE RecursiveDo      #-}
-----------------------------------------------------------------------------
-- | The header's hollow mark, ported from the source's @HollowMark.purs@ and
-- @HollowMark.ts@. WebGL1, one instance, drag to spin.
--
-- The pure reference mesh is generated by 'Site.HollowGeometry'; a build step
-- emits the same mesh as milli-unit text for the browser. It is decoded into a
-- @Float32Array@ through one JavaScript helper call, then uploaded once. The
-- moon texture loads asynchronously and is re-uploaded on load.
module Site.Widgets.Hollow
  ( mount
  ) where
-----------------------------------------------------------------------------
import           Control.Monad (void, when)
import           Control.Monad.Trans.Class (lift)
import           Control.Monad.Trans.Maybe (MaybeT (..))
import           Data.IORef
  ( IORef
  , newIORef
  , readIORef
  , writeIORef
  )
import           Prelude hiding ((!!))
import           Miso.DSL
  ( JSVal
  , create
  , fromJSValUnchecked
  , jsg
  , jsgf
  , jsNull
  , new
  , setField
  , (!)
  , (#)
  , (!!)
  )
import           Miso.String (MisoString)
-----------------------------------------------------------------------------
import           Site.Canvas (rasterLayout, rasterCanvasHeight, rasterCanvasWidth)
import qualified Site.Config as Config
import           Site.Hollow
import           Site.HollowGeometry (hollowVertexCount)
import           Site.Platform (prefersReducedMotion)
import           Site.Widgets.Gl
import qualified Site.Widgets.Browser as Browser
import qualified Site.FrameLoop as Frame
import           Site.Widgets.HollowGeometry (hollowGeometryText)
import           Site.Widgets.Shaders (hollowMarkFragment, hollowMarkVertex)
-----------------------------------------------------------------------------
data Uniforms = Uniforms
  { uniformAngle     :: JSVal
  , uniformCubeAngle :: JSVal
  , uniformAspect    :: JSVal
  , uniformTime      :: JSVal
  , uniformLabHover  :: JSVal
  }
-----------------------------------------------------------------------------
data HollowLive = HollowLive
  { hollowCanvas       :: JSVal
  , hollowGl           :: JSVal
  , hollowProgram      :: GlProgram
  , hollowBuffer       :: JSVal
  , hollowTexture      :: JSVal
  , hollowImage        :: JSVal
  , hollowVerticesAt   :: Int
  , hollowUniforms     :: Uniforms
  , hollowStartedAt    :: Double
  , hollowReduceMotion :: Bool
  , hollowState        :: IORef HollowState
  , hollowHover        :: IORef Double
  , hollowSize         :: IORef (Int, Int)
  , hollowIntersecting :: IORef Bool
  , hollowLoop         :: Frame.FrameLoop
  , hollowPrevious     :: IORef (Maybe HollowUniforms)
  , hollowScope        :: Browser.Scope
  }
-----------------------------------------------------------------------------
-- | The mesh as a compact build-generated milli-unit payload: each quantized
-- value has 0.001 precision, and the JavaScript side decodes it to floats in
-- one call. This avoids a runtime float formatter and the cost of evaluating
-- all trigonometry during page startup. 0.001 is far below what a 16-pixel
-- mark can show.
--
-- Built once, decoded by one JavaScript function call into a @Float32Array@;
-- passing 300k numbers across the FFI individually would be slower than the
-- rest of the mount combined.
-----------------------------------------------------------------------------
mount :: Browser.Scope -> JSVal -> IO Bool
mount owner canvas = do
  context <- createWebGlContext canvas
  case context of
    Nothing -> pure False
    Just gl -> do
      scope <- Browser.newScope
      Browser.own owner (Browser.disposeScope scope)
      Browser.own scope (releaseContext gl)
      built <- build scope canvas gl
      case built of
        Nothing -> Browser.disposeScope scope
        Just _ -> pure ()
      pure True
-----------------------------------------------------------------------------
createWebGlContext :: JSVal -> IO (Maybe JSVal)
createWebGlContext canvas = do
  options <- create
  setField options "alpha" True
  setField options "antialias" True
  setField options "depth" True
  setField options "premultipliedAlpha" True
  context <- canvas # "getContext" $ ("webgl" :: MisoString, options)
  absent <- isAbsent context
  pure (if absent then Nothing else Just context)
-----------------------------------------------------------------------------
build :: Browser.Scope -> JSVal -> JSVal -> IO (Maybe HollowLive)
build scope canvas gl = runMaybeT $ do
  program <- acquire scope (compileProgram gl hollowMarkVertex hollowMarkFragment "hollow-mark") (deleteProgram gl)
  buffer <- acquire scope (createVertexBuffer gl program) (\value -> void $ gl # "deleteBuffer" $ [value])
  texture <- acquire scope (createMoonTexture gl program) (\value -> void $ gl # "deleteTexture" $ [value])
  lift (createLive scope canvas gl program buffer texture)
-----------------------------------------------------------------------------
createVertexBuffer :: JSVal -> GlProgram -> IO (Maybe JSVal)
createVertexBuffer gl program = do
  buffer <- gl # "createBuffer" $ ()
  absent <- isAbsent buffer
  if absent
    then pure Nothing
    else do
      vertices <- geometryArray
      void $ gl # "useProgram" $ [glProgram program]
      void $ gl # "bindBuffer" $ (glArrayBuffer, buffer)
      void $ gl # "bufferData" $ (glArrayBuffer, vertices, glStaticDraw)
      position <- attribLocation gl program "a_position"
      surfaceNormal <- attribLocation gl program "a_normal"
      region <- attribLocation gl program "a_region"
      let stride = 7 * 4
      vertexAttribute gl position 3 stride 0
      vertexAttribute gl surfaceNormal 3 stride (3 * 4)
      vertexAttribute gl region 1 stride (6 * 4)
      void $ gl # "enable" $ [glDepthTest]
      void $ gl # "depthFunc" $ [glLequal]
      void $ gl # "disable" $ [glCullFace]
      pure (Just buffer)
-----------------------------------------------------------------------------
createMoonTexture :: JSVal -> GlProgram -> IO (Maybe JSVal)
createMoonTexture gl program = do
  texture <- gl # "createTexture" $ ()
  absent <- isAbsent texture
  if absent
    then pure Nothing
    else do
      void $ gl # "activeTexture" $ [glTexture2]
      void $ gl # "bindTexture" $ (glTexture2D, texture)
      void $ gl # "texParameteri" $ (glTexture2D, glTextureWrapS, glRepeat)
      void $ gl # "texParameteri" $ (glTexture2D, glTextureWrapT, glClampToEdge)
      void $ gl # "texParameteri" $ (glTexture2D, glTextureMinFilter, glLinear)
      void $ gl # "texParameteri" $ (glTexture2D, glTextureMagFilter, glLinear)
      white <- whitePixels
      texImage2DWith gl glTexture2D 0 glRgba 1 1 0 glRgba glUnsignedByte white
      moonUniform <- uniformLocation gl program "u_moon_texture"
      void $ gl # "uniform1i" $ (moonUniform, 2 :: Int)
      pure (Just texture)
-----------------------------------------------------------------------------
vertexAttribute :: JSVal -> Int -> Int -> Int -> Int -> IO ()
vertexAttribute gl location size stride offset = do
  void $ gl # "enableVertexAttribArray" $ [location]
  void $ gl # "vertexAttribPointer" $
    (location, size, glFloat, False, stride, offset)
-----------------------------------------------------------------------------
-- | @new Float32Array@ from the packed geometry string.
geometryArray :: IO JSVal
geometryArray = do
  constructor <- jsgf "Function"
    ( "source, vertexCount" :: MisoString
    , "const bytes = atob(source); const out = new Float32Array(vertexCount * 7); let bit = 0; const readBits = width => { let value = 0; for (let offset = 0; offset < width; offset++) { value |= ((bytes.charCodeAt(bit >> 3) >> (bit & 7)) & 1) << offset; bit++; } return value; }; for (let vertex = 0; vertex < vertexCount; vertex++) { const base = vertex * 7; for (let field = 0; field < 6; field++) out[base + field] = (readBits(11) - 1024) / 1000; out[base + 6] = readBits(3); } return out;" :: MisoString
    )
  constructor # "call" $ (jsNull, hollowGeometryText, hollowVertexCount)
-----------------------------------------------------------------------------
whitePixels :: IO JSVal
whitePixels = do
  constructor <- jsgf "Function"
    ("return new Uint8Array([255, 255, 255, 255]);" :: MisoString)
  constructor # "call" $ [jsNull]
-----------------------------------------------------------------------------
createLive :: Browser.Scope -> JSVal -> JSVal -> GlProgram -> JSVal -> JSVal -> IO HollowLive
createLive scope canvas gl program buffer texture = mdo
  uniformAngle <- uniformLocation gl program "u_angle"
  uniformCubeAngle <- uniformLocation gl program "u_cube_angle"
  uniformAspect <- uniformLocation gl program "u_aspect"
  uniformTime <- uniformLocation gl program "u_time"
  uniformLabHover <- uniformLocation gl program "u_lab_hover"
  startedAt <- performanceNow
  reduceMotion <- prefersReducedMotion
  hover <- readLabHover canvas
  state <- newIORef (initialHollowState startedAt)
  hoverRef <- newIORef hover
  size <- newIORef (1, 1)
  intersecting <- newIORef False
  loop <- Browser.frameLoop scope reduceMotion (drawFrame live)
  previous <- newIORef Nothing
  image <- new (jsg "Image") ()
  setField image "decoding" ("async" :: MisoString)
  let live = HollowLive
        { hollowCanvas = canvas
        , hollowGl = gl
        , hollowProgram = program
        , hollowBuffer = buffer
        , hollowTexture = texture
        , hollowImage = image
        , hollowVerticesAt = hollowVertexCount
        , hollowUniforms = Uniforms {..}
        , hollowStartedAt = startedAt
        , hollowReduceMotion = reduceMotion
        , hollowState = state
        , hollowHover = hoverRef
        , hollowSize = size
        , hollowIntersecting = intersecting
        , hollowLoop = loop
        , hollowPrevious = previous
        , hollowScope = scope
        }
  loadMoon live
  applyLayout live
  registerPointer live
  registerResize live
  registerTheme live
  registerHover live
  registerVisibility live
  pure live
-----------------------------------------------------------------------------
loadMoon :: HollowLive -> IO ()
loadMoon live = do
  Browser.listen (hollowScope live) (hollowImage live) "load" False $ \_ -> do
      let gl = hollowGl live
      -- Set the unpack flag only for the image upload. It must not surround
      -- the typed-array placeholder upload during context setup.
      void $ gl # "pixelStorei" $ (glUnpackFlipY, 1 :: Int)
      void $ gl # "activeTexture" $ [glTexture2]
      void $ gl # "bindTexture" $ (glTexture2D, hollowTexture live)
      void $ gl # "texImage2D" $
        (glTexture2D, 0 :: Int, glRgba, glRgba, glUnsignedByte, hollowImage live)
      writeIORef (hollowPrevious live) Nothing
      startLoop live
  setField (hollowImage live) "src"
    ("/assets/images/lroc-color-1k.webp" :: MisoString)
-----------------------------------------------------------------------------
-----------------------------------------------------------------------------
readLabHover :: JSVal -> IO Double
readLabHover canvas = do
  value <- canvas # "getAttribute" $ ("data-" <> Config.labInteractionKey)
  text <- fromJSValUnchecked value :: IO (Maybe MisoString)
  pure (if text == Just Config.labInteractionHovered then 1.0 else 0.0)
-----------------------------------------------------------------------------
applyLayout :: HollowLive -> IO ()
applyLayout live = do
  let canvas = hollowCanvas live
      gl = hollowGl live
  rect <- canvas # "getBoundingClientRect" $ ()
  width <- fromJSValUnchecked =<< rect ! "width"
  height <- fromJSValUnchecked =<< rect ! "height"
  when (width >= 1.0 && height >= 1.0) $ do
    window <- jsg "window"
    ratio <- fromJSValUnchecked =<< window ! "devicePixelRatio"
    let layout = rasterLayout width height ratio 1.0 6.0
    writeIORef (hollowSize live)
      (rasterCanvasWidth layout, rasterCanvasHeight layout)
    setField canvas "width" (rasterCanvasWidth layout)
    setField canvas "height" (rasterCanvasHeight layout)
    void $ gl # "viewport" $
      (0 :: Int, 0 :: Int, rasterCanvasWidth layout, rasterCanvasHeight layout)
    writeIORef (hollowPrevious live) Nothing
    startLoop live
-----------------------------------------------------------------------------
drawFrame :: HollowLive -> Double -> IO ()
drawFrame live timestamp = do
  state <- readIORef (hollowState live)
  hover <- readIORef (hollowHover live)
  (canvasWidth, canvasHeight) <- readIORef (hollowSize live)
  let input = HollowInput
        { hiTimestamp = timestamp
        , hiStartedAt = hollowStartedAt live
        , hiReduceMotion = hollowReduceMotion live
        , hiLabHoverTarget = hover
        , hiCanvasWidth = canvasWidth
        , hiCanvasHeight = canvasHeight
        }
      (stepped, uniforms) = hollowFrame input state
  writeIORef (hollowState live) stepped
  previous <- readIORef (hollowPrevious live)
  when (previous /= Just uniforms) $ do
    drawUniforms live uniforms
    writeIORef (hollowPrevious live) (Just uniforms)
-----------------------------------------------------------------------------
drawUniforms :: HollowLive -> HollowUniforms -> IO ()
drawUniforms live uniforms = do
  let gl = hollowGl live
      Uniforms {..} = hollowUniforms live
  -- Keep the program association explicit. Resize/theme callbacks can run
  -- after another WebGL operation has changed the current program.
  void $ gl # "useProgram" $ [glProgram (hollowProgram live)]
  void $ gl # "clearColor" $ (0.0 :: Double, 0.0 :: Double, 0.0 :: Double, 0.0 :: Double)
  void $ gl # "clear" $ [glColorDepthBits]
  void $ gl # "uniform1f" $ (uniformAngle, huAngle uniforms)
  void $ gl # "uniform1f" $ (uniformCubeAngle, huCubeAngle uniforms)
  void $ gl # "uniform1f" $ (uniformAspect, huAspect uniforms)
  void $ gl # "uniform1f" $ (uniformTime, huTime uniforms)
  void $ gl # "uniform1f" $ (uniformLabHover, huLabHover uniforms)
  void $ gl # "drawArrays" $
    (glTriangles, 0 :: Int, hollowVerticesAt live)
-----------------------------------------------------------------------------
startLoop :: HollowLive -> IO ()
startLoop = Frame.invalidate . hollowLoop
-----------------------------------------------------------------------------
addListener :: HollowLive -> JSVal -> MisoString -> Bool -> (JSVal -> IO ()) -> IO ()
addListener live = Browser.listen (hollowScope live)
-----------------------------------------------------------------------------
registerPointer :: HollowLive -> IO ()
registerPointer live = do
  let canvas = hollowCanvas live
  addListener live canvas "pointerdown" True $ \event -> do
    Browser.capturePointer canvas event
    handlePointer live HollowDown event
    markDragging live "true"
  addListener live canvas "pointermove" True (handlePointer live HollowMove)
  addListener live canvas "pointerup" True $ \event -> do
    handlePointer live HollowUp event
    markDragging live "false"
  addListener live canvas "pointercancel" True $ \event -> do
    handlePointer live HollowUp event
    markDragging live "false"
-----------------------------------------------------------------------------
markDragging :: HollowLive -> MisoString -> IO ()
markDragging live value =
  void $ hollowCanvas live # "setAttribute" $ ("data-" <> Config.hollowDraggingKey, value)
-----------------------------------------------------------------------------
handlePointer :: HollowLive -> HollowPointerKind -> JSVal -> IO ()
handlePointer live kind event = do
  void $ event # "preventDefault" $ ()
  let canvas = hollowCanvas live
  rect <- canvas # "getBoundingClientRect" $ ()
  width <- fromJSValUnchecked =<< rect ! "width"
  x <- fromJSValUnchecked =<< event ! "clientX"
  y <- fromJSValUnchecked =<< event ! "clientY"
  timestamp <- performanceNow
  state <- readIORef (hollowState live)
  writeIORef (hollowState live)
    (hollowPointer
      (HollowPointerEvent kind x y timestamp width)
      state)
  startLoop live
-----------------------------------------------------------------------------
registerResize :: HollowLive -> IO ()
registerResize live = do
  options <- create
  void $ Browser.observe (hollowScope live) "ResizeObserver" (Just (hollowCanvas live)) options (\_ -> applyLayout live)
-----------------------------------------------------------------------------
registerTheme :: HollowLive -> IO ()
registerTheme live = do
  document <- jsg "document"
  element <- document ! "documentElement"
  options <- create
  setField options "attributes" True
  void $ Browser.observe (hollowScope live) "MutationObserver" (Just element) options (\_ -> startLoop live)
-----------------------------------------------------------------------------
registerHover :: HollowLive -> IO ()
registerHover live = do
  options <- create
  setField options "attributes" True
  void $ Browser.observe (hollowScope live) "MutationObserver" (Just (hollowCanvas live)) options $ \_ -> do
    value <- readLabHover (hollowCanvas live)
    writeIORef (hollowHover live) value
    startLoop live
-----------------------------------------------------------------------------
-- | The source gates the loop on intersection with a 120px margin and on tab
-- visibility; reduced-motion users get a single frame per change instead.
registerVisibility :: HollowLive -> IO ()
registerVisibility live = do
  options <- create
  setField options "rootMargin" ("120px" :: MisoString)
  void $ Browser.observe (hollowScope live) "IntersectionObserver" (Just (hollowCanvas live)) options $ \entries -> do
    first <- entries !! 0
    intersecting <- fromJSValUnchecked =<< first ! "isIntersecting"
    writeIORef (hollowIntersecting live) intersecting
    emitVisibility live
  document <- jsg "document"
  addListener live document "visibilitychange" False (\_ -> emitVisibility live)
-----------------------------------------------------------------------------
emitVisibility :: HollowLive -> IO ()
emitVisibility live = do
  intersecting <- readIORef (hollowIntersecting live)
  document <- jsg "document"
  visibility <- fromJSValUnchecked =<< document ! "visibilityState"
  let visible = intersecting && visibility == ("visible" :: MisoString)
  Frame.setVisible (hollowLoop live) visible
