// Embeds the GLSL sources in shaders/ as MisoString literals so the wasm bundle
// carries them. WebGL cannot run during prerender, so the shaders are data, not
// files fetched at runtime.
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const shaderDir = join(root, 'shaders')
const outFile = join(root, 'generated', 'Site', 'Widgets', 'Shaders.hs')

const camel = (name) =>
  name.split('-').map((part, index) => (index === 0 ? part : part[0].toUpperCase() + part.slice(1))).join('')

const haskellName = (file) => {
  const [base, extension] = file.split('.')
  return camel(base) + (extension === 'vert' ? 'Vertex' : 'Fragment')
}

const files = readdirSync(shaderDir)
  .filter((file) => /\.(vert|frag)$/.test(file))
  .sort()

if (files.length === 0) {
  console.error('shaders/: no .vert or .frag files found')
  process.exit(1)
}

const entries = files.map((file) => ({
  file,
  name: haskellName(file),
  literal: JSON.stringify(readFileSync(join(shaderDir, file), 'utf8')),
}))

const header = [
  '-- | Generated by scripts/shaders/generate.mjs from shaders/. Do not edit.',
  '--',
  '-- Regenerate with @make shaders@. The literals are the GLSL sources',
  '-- verbatim; editing them by hand will be overwritten.',
  '{-# LANGUAGE OverloadedStrings #-}',
  'module Site.Widgets.Shaders',
  '  ( ' + entries.map((entry) => entry.name).join('\n  , '),
  '  ) where',
  '-----------------------------------------------------------------------------',
  'import           Miso.String (MisoString)',
  '-----------------------------------------------------------------------------',
].join('\n')

const body = entries
  .map((entry) => `-- | @shaders/${entry.file}@\n${entry.name} :: MisoString\n${entry.name} = ${entry.literal}\n`)
  .join('\n')

mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(outFile, `${header}\n${body}`)
console.log(`shaders: embedded ${entries.map((entry) => entry.file).join(', ')}`)
