// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Internal__Dust_Syntax$Dust = require("@fahmiirsyadk/dust/src/Syntax/Internal__Dust_Syntax.js");

function main(param) {
  return Curry._2(Internal__Dust_Syntax$Dust.Html.Elements.html, /* [] */0, {
              hd: Curry._2(Internal__Dust_Syntax$Dust.Html.Elements.link, {
                    hd: Curry._1(Internal__Dust_Syntax$Dust.Html.Properties.rel__link, "Stylesheet"),
                    tl: {
                      hd: Curry._1(Internal__Dust_Syntax$Dust.Html.Properties.href, "/assets/css/styles.css"),
                      tl: /* [] */0
                    }
                  }, /* [] */0),
              tl: {
                hd: Curry._2(Internal__Dust_Syntax$Dust.Html.Elements.body, /* [] */0, {
                      hd: Curry._2(Internal__Dust_Syntax$Dust.Html.Elements.h1, {
                            hd: Curry._1(Internal__Dust_Syntax$Dust.Html.Properties.class_, "mx-auto text-center text-purple-500 font-bold text-6xl mt-12"),
                            tl: /* [] */0
                          }, Curry._1(Internal__Dust_Syntax$Dust.Html.Elements.text, "Coming soon")),
                      tl: {
                        hd: Curry._2(Internal__Dust_Syntax$Dust.Html.Elements.p, /* [] */0, Curry._1(Internal__Dust_Syntax$Dust.Html.Elements.text, "ini deskripsi")),
                        tl: {
                          hd: Curry._2(Internal__Dust_Syntax$Dust.Html.Elements.img, {
                                hd: Curry._1(Internal__Dust_Syntax$Dust.Html.Properties.src, "/assets/images/makima.png"),
                                tl: {
                                  hd: Curry._1(Internal__Dust_Syntax$Dust.Html.Properties.alt, "makima god"),
                                  tl: /* [] */0
                                }
                              }, /* [] */0),
                          tl: /* [] */0
                        }
                      }
                    }),
                tl: /* [] */0
              }
            });
}

var H;

var P;

exports.H = H;
exports.P = P;
exports.main = main;
/* No side effect */
