let greeting = j`Hi, i’m fahmi. On this site you will literally find collection of poetries, notes, thoughts, or anything comes up into my mind.`

module SEO = {
  let title = "fahmiirsyadk"
  let description = greeting
  let ascii = "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
          ..'..
. ....',:,''......''.,,'''
... ... .........,'.,;';c;,,',;,,'..',;;','
.'';,,:;;',,''.........  .'..'.'ll:::,...,;,::;;
... .   ..  ..        . .'::'',,'''.,.....         ,;,,:;;c,;:','...',;'.:
.....',,;'.     .. ..         .......''''''',;...''...'....,'.....'':oool:l:;'',..,,,;','...
.. ...';';,..................,:'';.',..',,'..''.'',,''''..,,,';:';;;;;,:c::,,..,;,;,,;,;,,,.
....    ...'....';;,,''.',::;:;'......',c:,;,'....,'.'''.',.''.....;,,,,;.,:',..;'',;::cl:cc;;;',;,,. 
.'..'..',,,'',,',,,',;'';,'',;,:;,,:c,,,,..;;,:ccc;';,'''',,..,;;;,::;;;;,;,,,,',;,,;;,;,',....,,;ccc,:c,c:;:;.
..                  .';;',,';,;''.';.....,;,;,';,,;',:cl:cl:::,:c::ccc;;;,;::c;,,;;'',;;,,;;;;:l:,;;',cc;,,;;,,...';',.... ...,;';;',;';c;
.   .';c;,;.              .;cc::,...;:'',,'.....;,';.    ....'ccll:ol,::,;;;;;,;;,..'..'.,..;;,;',c;colcl:,'';;;,,;',,....'..'.,...,cc,;,...'''',
..'.'''..;dxdlc,;,.       ...'..:ld:;::;,......'::;;;'.     ..'',;;;:::;,;..;cc:;,''...'.. ........,.,;:llloc:o:,:,,;::;;',;',,',. .     .cc;,'.'..,,;,
.  ..''..':cldxkkxooo:;'.. ..';;,:c;;;cdlc;;;..       ....  ..';;:::ccl:'';;',;,,;;:;''''.'','..........,,cllll:cc,'..''::;c;,'',''','.........'',,'..'..',,
....'',.......  'cc;:c::;;:,.,cl:;c::::llodxkxodl::,',...,,';'.. ,c;;;:;,::,,''''''',cl:c:;:,,;,,;,,',;:'',.....':;,:,,::;''';c;,;;:;';,,;;,';'.'',.,,',''''''';''
.';c:,'';c;;;'''...'...  .;:cc,;ocooccll:;cl::ol::cc;;c:::,:;.';,''.,,;;;,;;,',..,','';',:;::;,';;',;';;,:c;;c:;''''',,',,,;;;;:cc;;;,''',,,'''','';,';,'.....  ..  
. ..       .'',;::,..'.  .  ...'.',,cl:clddool:l:',;,;c:;;',;;:;,cc:c:ccc;,;,....''',,,',. .''..;::,',:::,,,...''.;;''.';....,....,:lclol:;::;;;,'',:,,;''... .  ..'.            
..... ... ..  .   .........''';:;ccclclllcclolcoo:lc;;,c:::,',c:,;c:c::l::cc,,:,:;''',;''..'...,::;';,.','..      ..       ...     ..'ccc:clcccllcol;cc;,.          .... .          
.. .........  .....        .'..'. ....   .....,',;;:lcc:;;;;cllollllodololllc:ddolcc:c:;:lollcl:clc:cll:ll,;;:c;::,''.....  ...;,.'... ..  ........  . ...... ..'ll:cll:;ccddoxoooloo:;'       .........,.'.      
...'.'..;'.;:,,;'...  ..     ..  ......'. ...''',,;;;lddxdddcododolooldoxdxxoddxcodolloc;lolll::lll;cc:lcox:;::;;:;;cc;;c:c:.'.  . . .  .'....:;'..  ........''''',,..:;cdlcooxkdoo:;;:c:lc:c:;;,,,....,...       ...  ... . 
',,;;l;,:,,;,',:;,.....    .....;,,lc:c;',,,,clccl,.. .,;:odkxxkxxkxdxxddodlcdolododxooloo:dd:c::c:cllodloxoll,,cc;c:';:::ccc:,;,'..... .  .   .... ....''..,'.'''';;:::ldxxkolodxxdoolccc::c,'.. ...',,.'.         .'.........
..',;;;''c:;,',,:c:,;:;'.'';c;:;'::,,,.;ldxoocclccc::ccoododkddddodxxxxxdddooxollodooxodoldcodlocloldodxxooo:cc;c:;::;,;.'c:cl:::;;'......''..........,,'.....',:ddxOOOxoooooddolll::c;'':;:c:;....',';:;,.. .........''......,.
. .     ...';:::;::,;;;ccclllc:cl:c:cc::,'''. ..';oocoo,,;c::looxkxxkkxkxoxxollc:lloddxoldooo::llllollooxddkodkdxdcdocoocco:,;;;,'.';::;c;;:,;;''''','','''....,,. ..'cxxdkkxOxkkxkol:::ccldoolc:,...,;cc;'',,.,'...   ...........'.,:;cc
.    .         ....    .';;clccoc;:c;,,::;:::c:;:..c::odo::llc;';c:dkoddoc:,;c,:lclododxkkkkkxooooocodolol;:c;;;;:llodcclcclododxxxlxodxll:ol;cc::;;:;;;';;''',;,;,;;,',,.';',;'.'''''.'coolc:c:;:,;,,;;,,:;;;;;;;. .....'''..........'.....'..'.... .'.,,
..  .;'..   ..',...  .'',,,,.':;cc;:l::c::ccclcll:c:;:c:c;''::;ldooxxxdocdkoOkdxl:cc;:;,::,;cldodkdxxdxxoxdllollocc::cc;:llll:cc::lc:oo:;clc;,;,.'..,;,::,;c:;:;;;'';;;,;;',,''.,;;;;;,..,'.'....   ...  .. ...''.;:''',;;'''''',,......'.'..... ',;::::;,:'.. .. 
........   .       .''....,;,';;:ll:;c,,lo;'.... .;;cc,,;',;;c;;oc,:c;colodl::codxddc:oc:l::loloooccloxololllllddlollooc:;:c;,,,:;,;,cl:,'':c:llcloc:;.''.'','';.'cc:cc:clollol:;c:;;:l:;:,.'..';','.'...'.'..' .'..'.,;.',:;::,;:,;;',,'....''.......'..'',;,;c,::;;.'. 
.'''''''..,,,,..''',,,..,..:;:c,:c:,.';,.'.     .;;;;''....,ldxlcc;c:,;:cllclccclocc::oc,,'';looxxdkOoddcoooodoodllllccccc;;;,:clc:;:cccc;.',.';llcl:,':c::;:;,:::ll::locclllccoc,;::,,;::,,:::::c';:'.'.':;''. ',..'';,,,'',;::,.,,,:,....'..'';;:::;,'...';.,:,,:;,;;''
.,'.',c::clc:;::;:c;........  ..,'';;,c:;:...    .:,.',,;,..:ooxoooldc;c;;cccol::;;lcll::,,:;,cc:::cccolccodddxodolc,'cc,,'.',..;:lc::clcl::;,;:::c:;:c:;lo,:llo:cloddodxldoodloccc,,;;;',:;,;;ccccl;:o:;,;'.;;'..,;:;,;:c,,,...,::,'.;:...... .,,,;:;,'';.,;''''...';,..,'
..  ......... ...'.......,. .....';;';lc;:::lcl:...';;,..  ... .         ........   .,,.. .;;,..,::cc:clllloooolc:ccccccll:,,;:llol::cccc;;clccc:clloolllc::;::::c:ccll:c::c::;:olcooclllldlcdlcclllllllc:c:lccc:c;;:;;::;,:;;l,.;;;,;:,;:cc;;;;;c,...... .;;:c;.,,;;,:'..'...      ....'',;:;;:;,,,,.....',,,'
..''';:',,::;:cccccllodllc;,'';c:'''..;:;,.'ldxxlcc,';,..,',::' .';:;.    ...;,...           .;'. ..     'cclc:;;ccclloloddollclllllllllodc:llclccoooccl:cdc;:lldxxkkkkxo:;:,::;c;::'.,'.......':ldlc;:c:llooloolll::l:;;:cclc::,;,',:c:c;::;cl;';;,,,,........'..  ......',,:c;;lccclc:c:,......     .,,'...,:;:,';;'',,..;'.
.,;;:colloldooollooloodoodolcdo;',c:'.'ccol'.. 'cddl;,;..   .. .      .'.    ...:c,;,     . ... ,do:'.'''.. .';c;:llodxxxkooool:c:loodoodlcxxxxooocc;;clcloclolodlloclxxxkdoo:;,,;;...               ';;;:::;,:l,;:c::ooc;..,,;,'''.......',..,'',;:;,,,,'....'.... .'',:,:c,c:.,c:,:::;:c::::::,,;,'.,,',,,l;....',;,'';:'..;:..
.,,',lc;,;cdodkxdlollcccll::::cc;:clodxc;;,:c:::,..';lco:..,...''          ..   .cc;;:;,;.....   .  .,:'.::;,.''',;';;:ooxolccol:,:c:cdxddxooolllooclooo:::;;:lldOoodl::,;c:;:'... .',....                 .,:c:'.,::ccolldc.   .''''.             ',.':,.'.':;''..  .   ';'..,,',;'',cc:lo:l:,:;;:;,,c:,cc:c;;;cl:c;;'.;'',':::c:cc:
';'..'c::c;loodlclddolc,':;;cllldoodddllloooccl:,'..'..,.     ;;..          ..   ',.,,,'...';,,.  .c'';'''';'',..,',clc::,....'';'....';,',,,,:;':,.,:;;..  .....',:ll;,'.....      .','                    .....  ...''''''.               ...  . .';cc:,'.....:;.       .      ...'....;'';.';cc:c;',;::;,'',;,;:,;c,;:,;::lc:c::::
......':odlldlldddc:::olcldlddlccoodoodoooloc:oo:;::;;cc'.. ';c:. ..    ....    ..,;:cc:...,'.'. .cl;,:cccldlcc;c:..;:.''.               ..         ...           .,';:;:,...       ..,,                                              ..',....       .....'  ...''                .         ....,c:,;,';...  ...:;:llc,,lc;,:c;;c:;;,
.  .             . .''....'oxl;,;llcll:lclodOOOOOkdddllc:cl:oxdocc;....;o:'',;:cc:,..c:';occl,..  .. ...;l:'..;'.';',cl:,'',coc,,'';....'.                  ....                  .. .',,;;:;''''.. ...'..;,;c'                                   .  .     ...'.                 .''....  ..        .'.  ........     .';;c:... ..;cllollc;:c,...',','..
.,;:;;.....  ..     .'',;.......'dxoddocokOOkOOO0OxOkdxdoxoldc,..;;:c:,.','.',,,,';:co:;' .',....;;;cc;';,...',',;;,....,:;c:''.'.....     .',,'......,',;'........''',,,;:;,;:,'''..,,::,,,;;,,,'..;;:;,:;'',..                     .  .  .         ..'.;;.. .  .  .         ...,'.'..'..'.   .'....'................''..;:::dodOxddl::;'. .. ...  
. ..  ..     .,lxkxdddcol,''.  .',.''.,;:;,''..';:;cdcodoxocddooxodOdx0kdxxOklcc:;:c:oc;loc,';:lloc..'cc;:,,;:c,;;,,,,....'.       .'',,..:lldo:;:c;''..,..''colodllll;::;::'',,::,,,:;:;,;:c:::;,'...  ',....,:,'c:''';:,',:clo;'...'''.''.....                       . ..'''... ....'.         .  ...'',,',.   ..  ..       .'''....'..  .,cc;;;cdololoc;,;,'..''','
.....:;....  ....    .;::,.  .;l'     .;lcc;;clccollxo,;:::;lcokdkOOXNW0kOddocdxdddoodllddlclodl::lo::oocll:c::c:c:cl;;,.'.  . .'....   .'.;occc'..':;',,...         .',::l;','..       .';'.,....,,c;;:,;,','',;c::,.;,,,;l:,..',,,:c;:,.. ..,,.',,,;;;,'.......    .          .... ..  . ...               .   .,.... ..     .  .'..',''.         .,lclollo,coldl,.''..,,,cc
.'',',;;,......    .;;. .. ...'...;;'. .;:coocllodoloxkdddoc:l;,lc;;;;:cloxkO00kxxdlc,;coloxloxOkddll:llcc:ldlcc::;:lc,ckl:c;......';,''''.,lxo;:',l;.',....',.   ..       .,:c;'.          .,;,,:,.,,:c:,,:,,,.. .......  .. ...       .';:',..'.......',;;'...,'...    ....     ...'',.',..,',;:;...               .. ......     .      ...,;'        .',coccllldoolc:.....';';l
..co:;,.'.        .',',,';::cll:,,;,..',''....'::lxdddkOxdoodlodxo:;::'.'ldlododdddol:;:ddccl;:lldollodoc:,,cc,,;;c;.;c:;;cc:;. ......  ....;ldocc;..,......,;,::;:od;.     .''cl;','..''''''';;;''....,'....                .'. .. ...'...'.....      .'.,.    .'.                   ...'....',.,;;cc:,..         ''... .....     ...  ...    .,.  .   .';'.'..;;';;:loxdddoc;c;,c
......:ldl:ll;.       .'lc:ccccll:''',:ddollol:,';,';ccdko::okOkOOxxxx00dl;;;;oxodo:ldxkOxdxlc;:llood:':,;;,c;''..',''..;,'c'':.;:';'..   .....;:,',;,::cc;:;'..'.'',:ll;;ldl;cocl:';::';odloxdddo:;'.                            .,.,;'''''''..,';;,,..       .'..    .                     ..     ..'.';';:::;''.      .''..'. ..... .....         .           ....,;;'   .,coocol,,,''
.''';c;,''..;;;c:,'    .'''',:lddxxxxl''cldxddl;ldclodxolodxxdc:oxxdllkOOdlodoc,cl;:odoc:coooxdcc:;,..';,.  ....,;'','......',;::','..'':,...',l:. ....... ... .....  ...;'.;',;,;';c;.....  ,loloddooxlc;..  .. ..              ..'''.......     .'. .,,..              .....'...                 .. ....'...;,.:cc;'.        .............   ..''.....                 .'.;;.','';:'...  ...
....,o:. .';c;.   ..,,,,;'.';lxc';cl::clOkxdcl,'oxxoloxdoolcdxodxkxxocddxkodOc.'c:;,,:l::ddddxxxoc:. .,;'..','.'''.,'.......';;'............'..,...   ..    ....',,'.   .c:'',;',;''''''...  .,:oddooxo;:;';'',...'. ..'.....  ........   .. .....'.'';;::.',,'.;,,'','',;;;;;,,;,,;,.''''''....';;,;............,;::;,.........,,...',;c;'....  ..                     . .''';;';''c:..,;,','
. .:cl:;:c,...,.''..',:c;,:llloolodc;c:;::oxddxxddccoxdcclodoclodllccloOOddkkxxdxl,coccc:;cc,;:cc:;,'....'::;c;;:',,...''...,;;.,;''''.'' ......,'',...''::,;;'';cc:,''....'c:cc';lloo:c:;'.......',:cclcoc;c'..',;,,..,,.',,.,;;..,,....',;,;;,:,;:,;:c,,c;;;;,;:'':,';;,',;;;,,:;,;,.',,,;c:c;,,..'cccl;.':,,,::',;;;:::;,,''.  ....  .,;,;. ..,' .                   .'.     ....  ..;:::lodddo
.'. .'cxdxdlc:;''';;:dc':l::l;;;,cc::;'. ,:,,';;:lloxxkdoxo;.';;;:::c;;lldkOkdkxc,';:,.ld;:l,..',..'..     . ';';;;:;,;;.''.''''.'cl;,;::;,:'.. ';,,;,;;;,,,''..',;'.',;.  ...'::,cc::coxxxxolcldoc;cl;ldlc:;:clc::;,;',c:;,;,;,;',:;,,:::c;;;;;,::':;,;,;,;,;c;;;;;;'.,:,,;:;;:;,,;;,;,;;'.''',';;;::c;,;;cc:,,::c:,;;;,,:;;:,;,,;','','',;c;.....'...''.        '..,'.,;,''.            .''.';,,:,;,
. .''cc;ldddoddlc,..'',';oddddoc,':;.  ..,;',:ccldo:':dodkkxxo:'';cxookxc;:ldxxdo;,'.    .,ldc,cl:,;,.........'....'c,cc:c,'.....;'..,::cccol::c;:c::l:,;'.''.      ...'',,,.',.,;;c:,;:;,'.:;:l;,;cccl;;l;,c:;;:ccc::;:;;;,;dl,;:c,;c;:;;;;:;,c;;::::c:::cc',;,;;clc:::;c,.'..''..;:,.'',;..',..',,':c;:c:;,,;'...,:,:c:,,:;,;;,,,:;:;,;;'....,:' ..   ....          ...,ll::c;.             .,co:;,,;..'
.',;.     ...:l,':oooooddxdxdllllc,....';llooc:ooc::cokdll;;:c:loodxdoddddkkkdcdkxddlcc,'',clc,.       .,:docoooc:c;;codokkddoclcdd:do;;'...,;;,'c:co::c;:l:,',:;;;,','',',...  .'.'...';,......':c,'' .',. ';'',:c;lo:cl;:c::;::lc:cl::c:cll::c:;,c;;,';',,,c;:c;,c:,::;,'...';;:c:llclo:,,'';..,'..,c..'.'..'.,::cclcc;:c:;',,';:;,;c;,;'',.',,,',,,'...'.',''',;'.'',..              .;''c:;.              .,cl:,lo::
.         .,.. .,:,.'.;dlcldoll::oOkoooodloc.   ..:ooo:cloxxkkkOdoooooodllodxl;,cddolokxodolcl;.;'';;:,.     .,:coc,:;:ollc;;;,:lollolokoxdlddloxc..... .'';;,''cc'.:o;':c;;cl:;::l:,;;:;''.,'......'',,.'';,..   ''.'.'l::lolodcccccll:;::c,;c:ll;:::c:;;llc:''.     .',;:;;,,';c;'';,':,.',;ccllc;,,;,:,';';oc:'.'.'.';,,,:,;:'',,',...;cl:c;';;;;'',..,;,;:,,.. ....'.,;'''.'..                   .','             .'.';;c:codd
.                 ....,c;,,;;:odxxdxoccoc,oc:cdxoodl;::,::,co:';xxxdooookK0ddOxllllxxcldl;:ddoxddddlcl;,;,,;;:c:;;;ldx0kll:;'.'.',',.';:olldxxxxkdclodl:cc;,,'.,cc,:l:;;;,;;;;.';';clc;;,',,';c:,;'';,,';llc'.;ooc::l:'';,,....:lloodc;o:co:;:;,;;cl,:c,::::.,:cx0Oxl:;. .  ..':;:'':,',::l:;c,,;;;',,c:,c:,;,;,.,'';;c:::..,. .;;,'',';:,;''''.,,,;'.;;,';,,;',',;';,';;..,..'''''...',,'....             .. .              ...'':ll,:dll
.,:'.             .',;lll:;;'.;dOxoxkxodd;;:'cdldl;,',;...;;:loclxOKOol:lxxkKKkkkkxxdoxdxkdxxlllloodooolc:lookxoxxxxdllxxxkddkd:;.....',cl;lo:;,coclol:lolcc::;,,;ccoc.;::'.... .. .',,:l;:c;:l::dl:,;:;;,.':cl:;cloc..:::c;;,.....,:ccl:,cc,:::;,;,:l:,;;,:;,:,,::cxol:,;..';'.',;;;,;,;..'':lcl:';lc;;;cl:c:,:;''';cc::,':ol:;;;.;:,'.....',..',;;,'',,..,'.''.;,,;,;;,,:lc;c:::;,,,.''.,,,...'........'.  ..                 . ...'coccodl
...,''..'.;c. ..   .....'':::oodo::c,,looxxdo,'...  ',:c':c;;'.,;;:olcoookKKKXKXK0kdollllkxxOxodxkxloddc:lclccxlcxxlccoxdlooodxdxdoxdollolcoccl:cc:;;::'':cdlco:,:l:,,;'',,,;ldlol;;;;::;:c:;c:;coocc;':lclolcclcc:::l:ldoc;:c''ll;;occccl;,;:lll:,:::ccc:;,,:;,;,;;,l:;::l:ccccc,,c,'cc::;,'';l::;,;,,;,:c:,:c;:::ccc;;c;,;,,'',;,;:ccc:,;;,cc;,c;',;,,,,';:.';'''';,....'..'..'...,;,;locc;';:;,',,,'''',...;:'';.                    .  ..'',:clldo
..     .,locol,',,;'.';,;,..';cc;;c:,,';lxc';:,,,:c:l;...    ,olcollddl:,;xKKKKKNWXNNXXKK0Oxkdoo;:oolddxxoodllddooocclldd:,::ll,.;cdkkxxxxolccol;,;cldlldolc:;'...;,,,.,;cc::;'....,:clodxxolcclollocclo:'clc;;l:,locllcldolc,:c::ll:::'.,cc:::::llll;;c:::';:;:;;:l:'coc;:clc;:ololclll,.';loc;clcc;;;.;ccc,:c:c:c:cc;;c;,:;c:;:;;;cc,:;.;l;;:,..,;;;,;;;;:c:;cc:c;,:;';;;;,'','....,,..'..  ...,;;,;;;,','',,,,,'.::;;;;,,'.       .'.          .  ...cc;,;:,,
.......  ..'',lc;;:;;:;,..:::;',::;cccl::l:cookdcc:cc;lxol:... .';cddokxok0kkkk0WWXNNX0OKKXXXXKKOxdcloodloolkOo:coxkxld0kddlll:';cll:''cdoccllll:,,'..,::dd;lo:::;'.......,,.;;;;.....,',x0ooxddccoccc:;,:occ;.;l:,;:;;od::llcolc;,::c;:lc:;,;cc;,'':o:;;lc;;::;;;::,',,:ccc;:;';'co:loll:cc;;,:occl::c:cl:'.;c::,,,;:cccoccl::c;,;::;',cccl:,,:l:,;;,.,,,,,;;;:;,:c:',;;;,;,;;,;,'.  ......;,. .'.'',,;.,;.;,..::'''''''':;,;,,',,     .             .'',;..,,::',;'
.          ',,,'co:c::c::;,',;;;;'.,'.,;:l,.',:lodxdoxxkkkxddddxo;,ld:lkkOOOkOOO00K0XWNWX0KK0K0O0kolollOK0Oo'',clloooOKx:cododdoo::lcc::lccl:;;cdkkxdo;..olcddlcdo::l:;....,,':,;c,',';:;cc:ldxxddo;;l:,:::::ll:clloollooooo::dlcc;ll,llc:;cclclolllc;,cc:llcll::cc:lcll::;:::cl:;,;,':c:;:c;:lc;',c:cl;',;;;,',;....;;;;:::lc:ccloc:c;;;',;;;ccc;,:;;,:;',;c:;:;;:;,;;;';;,;';:,;;;,,;,....'..',;',;..',,,,;'.:;'',,..,,',,,::'::,........                  ....,;;:,,:
....';::. .';;''',,'..';clcc;;,.. ..,ldokxcloolccol,:clxkxOOk0kldkxkOdOOk0XKKKO0OOOdxl:oko'  .;cxxldxxodkollcldoool:c::::ol;:oo:cl,:lcookxxkccllxkxooolokOdcc:;;;cc;cl:;:;:lddol:;;clolclloollcoocoxocldloocolld:colol;ccolcdodo;:cccccllllc:,:l;coddollododooxxdo:ccco:..'',,,:''::c;;;;;,;l:::;;,'....'.'cc:c:;::;;;..'..,,,;;;';::;::;;;;,:;;:;;;;cc,;;;:c;;c,;;';'.;:;;:';,.'';'.'.,;':;.'.'''';,,;.....''.;c;',:'';,,...                             .'..
.;. .'''...;c,.   ...    ... ,ox000x:::,,.....':'''.'';:..':oKNXKXNNXOK0oxkx0OxxdxkxOOxxxc,.  .;kOo:;,,,;oddxokxoxd:,,:llc,;ll;;:,::;;ldddol:colldddlldolxxxxodkxkko:::c:';:;cc:::coxkkddoccc;oxl:;col:coldlcooc;::clloloc;ldoc;ll:llddoocolc:cxxooddll,',;xkkOOkddlclooc:c:c:;;,;:'',,,,'':c;.':;;',c:lc';:,,'.....'.,::'.,;,;'':;'',l:;;;:;;;,::,::;;,;;c:,::;:;;;;;:;',,,.';..,.':,;,.'.':',;''',,,;;,. .'.....,:co:'.;;,;,''.,;,;'.                     ...',..,;:;
.,;c:c::;.                   .;.';;:;,'....               .,::,..  .          .,::;:coxxKNKKXKXKX0OK0OOkOOoookkdddool'      .;ccdOkoodxkOOOkxdddolccxxloccx:.''',oddxd:',clxxocllcxdc:;:oxdl:colo:'c:..'..;:;,,;:lccllolclcokxkd:c:':c:clodol:';olclc:cc::clod:;lllllll::lllxOkdllc..:oOWNXKKkdodd;;cclcclo:.;lcc;:c;:oolc,':c:cc;:l:::::,,,.'..,,:::c,;:;:;;;;:c::c;::;;;;:,;:,;;:c;;;;';c;;:;:';:,;''',.,;,,'','':,.'..,..,,'... .,... .. .',',;,;;'';;,''''',;:'              .    . .:lclc::;,;:
,oxdol:,.               .'','.,,,c, ..              ..                    ...,;''lddlcxOkO000kOKK0O0XKX0O0kdolodlooc;;'   .,;'';cllxOxdxlcdxdddoxkkdoooloo;;.  .. ..cool,.'cdOxdOOkxkOxclkxdood:,'',co::ll:oxdxdlloccodxl::cxxlcocol;:cc::;cc:dooooo;;:;ldlloloollllc;'.;ccodoooocod:;,',loxK0kxllo:,llcl:coc;;:::;:c;;cl::;;;,::;c:ccc;:lclcclclool:,;;;;cc,;:::;:c;,:c:;::::;;cl:.,c:;;,;;;::;:,,l:,,;,,,;,;c:;;;,;,,;,;,';,',;,.,;'','...';;,;;',;,,.,'..'''.''.                     ..':c::;::cc;
.,:llc'.              .,.,l:'... .'.                  ..               ..'''.'dkcckxO0doxOkkxkOOxkOk00K0k0Oxdddoddc;;c;..';;..''';dOxdxko:,.....;lkNKk0xl::o,.        .....':lldxdxkklllddodlllll:;'.'',ldk0KOx:';:;oxodxdoocco:;:;;ldl:;:'::,cllooollll::odlll:ll;lo:;;;':xxOXOddkOOO0Olc:.,:ll;:c::c,c:;cc::c:;,;:::;:cc;:;,clccc,;cc:;cccdololclccccc;;;,:c;c:,c::::;:lc;;c:c:;;c:;'':;;,::;:;;c::::;;:;',;'';,',;;:,:;.:c;:;',c;'',;',;,;,,;',;,'':c'''.;,,;''..                          ...  .':;
.....                  ...,.                                        ..;,;:;cc:dOocloOOxxkkoxxokxkOxkK00d:xolxk0OOdl::::kOxkOl...':dOdldxl:,......lK0k0KOdddo:,,..'..,;,,,;;';llloxocldkdcdO:.;c;.... .,:dko;,,...'..;clddccoccclo,.::co:;ccloc:xdlododolloooolodol;,..',..:kKNWNK0xlclccol:::ccll::::c:;:;cc;:l::c;;clc:l:;lc:cc:lccl;:c:cooooll:cc:cc:c:::::::c:c:;c;;c::c:::::;;::':lll;;l:;:::;::;c::cc;,:,;;;c:c:;,cd:';c:;c:',;c,;:;,;;',;,';,.,,,',,'.,.''... ..                              '::
.   ..                 .'''.....''......;:,....   .                      .;cc,'loxkododdoolllxOkkOkxdolddodddxkd'.',oOkdclc,..,oKkk0kko'cxkO000Xx;'.,;;;.'ckOxxxxkkdlodc,c,.'.,;',:l;.cdodxo;ldkkxxdkdxdlc::.   .,;::;;,;,;occloocccllc::c:cddlooc:c:clcxkdodxkOO0Oc;:llc;'.       .lxOOkxdl::::ccccllll:::;c:;c;:c:c::cc:cl::l::lc;cc;cocc::lllodccl:clllc:c::l::::c:cc::cc:lc,lo:cllcl:::;;,;:;;;'',;'..:oollc;;:c;cc..''';::ldll;ckxl:,,;;,,;;;;::.';;,;:,;;;;;;,;;..'.',;;.                            .',;c
.::..:l,          ...,,'';:,'.,c:'..  ....,,,,;;'.                    .,;,..:OOdoxkxkxodlcxdlocoxkkkkkolodlloc'''.'l0Okkl:;,,'',ldxOOx::cclcoxxOOkc',.:xoollxocoxdcdxo;ldcoo:cc;::,;dOo,,:dkxc. ,oxl::oO0kl;,lo:,,clc:c:;coloolodxo,:ololloooolcoc:dlcl:cdOOxOXXXNXXKkdoo'           ,looollll::coo:clcll::cc:lc:cl:;',:;cc:;cc;:l:;c:::cccololcllccoc;;;cll:;lc;c::c;;:;,,,;;;::;,c::c;::;c:::::;;;,,;'';:'cdc::,oddxll'     .;lo:''..dkol;;do,',;:;,:;''.';,;:',,''...''..'''.                      .''',,,:loll
.'',,. .,,''''..          .;cc:'';:,;,,,'.          ..                        .:xxcllcx0kdxddOOdddcdxooododxxkkxdoolcc,,;:clkKOkK0o' 'ddxOkxxdlcdxkOkdlodc:;;,,dOdddoxxl:lldc,cccldxooo;';:,lxkkxdxOdc;..,clc:clolc:cc;,:c:;cool::ol:cloloxl;:cclxd:lxkdlo:;,....';oXNKKKK0O00KXO:.  .'.',';;,:cccclccccc::oll::l::cc::;;:dko,...'::clccc,cd;;ll:cc:lool;'....;kklllll::c;cc:c;cc;c:;ccc:::::,;;,;;;;;;;c::,,,..'.':;oxdx:':odll:'.....'l00:',',llll:;ll;cl;',;',,.',;'.'';. ...''..... .   ...  ...  .'''',.';;'.'';,,;,;,
....  ..,;:l:;,',:;.        ....  ..,,.. .'';,.;.          ....    ....  .,'.     .:c;:odoclddxlx0O0kxkddxdololododdllccooc;:oook0O0kkKOOxl:.  'loxko,'';dkd:lxk0Oxl''';:cokxlcccc:::lc;clxkkkclx,.;;;oxOklcdxxddlllooollo:lc;' ...'..',,;;;cldo:cxxddl;;d0KkdodOo:,.         ;d0NNXK0xodxccc,;:::c:;cc:cclc:ccl:llccll;cllc:lcc:,;:ll;cl;;cl::l;:d:;::;:;'cdOKOx,. .',;:llcc:lc:::c;ccc;;;,c:;;;;;,c::;;;;:;:;:c::;;c;..... ..':dx;';;:;;;:;,..,.'::,;odc::,:c:c:;::;....'.',;cc:;::,','....'...   .  .,..''.   .''';,'',,.':c::,'''
..,lc.,,':,';...',;cllc,.            ''.... ..      ...';..     ....'....    .. .. ....'''..;d0kxkkOxxklloclk0x0Kxxxllxclxxccddooo:''...l;,dO0kxOooddc,. .;lokkkxl;;ckKx:;lxdodddoodddodxdoocclc:,::,;locoololcc::llcol:lccc:clddodkdccoodl;,;',cc:;cloc;loc:lo:;,...,cco0WWWKl.           .,lddxxkdodldl:lc:cc:;cllllccc:cllll:;ccccccc:cccc:lc:ll:cc:lclc:clccc:c:;;,:lllcl;':oooc'c:;o::cc:,l:,:cc;,:c:c;,:;:l:::,,;;:c;;c:,;c:;c:,c:;;',:;::c:;c:;:c;;:lococ. .,c::c;cdllc:;;:,'..,.';;:coccc:cdc;:,;;''''.....''.          .'........''''',,
...,::clllc;..;...',,::llc;.            ..;'    ...,:;;.            ..,.......          ';::;cdxxOO0kkKOKX00kclc:oxk0KKxOkdxdxkolclo:,,.;dddkKo;lddloxdc;,'cl,ckxxOOdoxxkxkK0OOdcocododocokooxxkxoooddl:c::ollc;cl:lddollolodocc;..,cxdco;cdc:collc';:clldxxxc;;....;kKXXXXXXNMMNXKOxdddkkdolodlolcolccclo:;lcclc:cdo:':l:;:clc;lc:c:cl:c::l:::ccll:lc:o:;c::cllcclc:;cc;::c:l:;llc;cccccclc;:cllc:ccc:c:ll;::::;;:;cl;:c,:d:':c,;c:,;,;:c::l:;'.'.,oolc::',c::::::c:,,;;,:c;',;''......;,',.,;;::::;,:llcccl,;;.';,..                 ..     .... .,,
.. ... .'.,ccdxo;;,,;;;:occodolo,..    .'';.  .  ...    .,cl::c;,..             ...     ....;,;,,oOxdkdoxkOKXKk0K00KKOOxll:oOOK00K0KxoOOxkOdoc;codONXkxkxoccdl:loc',''lc;lddxolkO0KkOK0xoocdlo0olxkxkkxdd0Kkdxlldooc:;;:,:lcl,;dd;,::cocl:',:llodooccloodxll:,:::lc:c;;. .;cdOKWMMMMMMMMMMMWXKKO0X0K0OK00K0K0Ooclllcccc;:ccl:ll:;:l:;ccl:;clc:c::clcc:;cccclc:cccll:;:cc::lclc:cl::c:c:cl:clllolooclollcclll:clcldlcdc,;:;cl;,:c;coc;;::,:l,;c;;:;;:;:l:,..'.,:;,.;;':';c;::;;c:;:;;cc,'.',,;;:c;....''',;;:cccccc:;,,;,;c;'. .                        ...'..';,
,:;clc:,'.:;':c:,.colloloood:coodol, .  'ldoc;....         .ccc:,:,.            .......'''',cc:;';x00XX0O0OoloOOKK00OOkxdlcoxdxkdxxol;:oxkOxoooxxx0X00K000O00xox0dlc:,,;lO0O0kkkddoxddkdodllodkxoll:coodoodOKOdoocoxxxxOklocclcollollldocc:c:;cooodkxd:;;,do:cccdo:,,,.,,   .xNWMMMMMMMMMMMMMNXWMW0kkdxdldodkxdddcclllc;:c::c:oc;cc:;ccccll::clc:clc::clc;cc:llc:cc:lc::ccc;:lclllcclllcodlldkxc:ldkdoolxxccodddllolol:lccc:cc:cc;;;:c:;,;c;,,;c:;;:;;:;,'',;,;,;:,;;,,'..'..:;'clcc;;''.,lc:lclc,:;.....'.,c,:ccldo::c,;,...                          .'':;,;''';'
..;:oxdlll:';,,;.''',;c;;oxxddddl;:cl;''..  ;::;,. .,;.      ..;oodoc;....   ...,,,;,;.  ...;ccddcddokOOOkOX0O0koodk0XXOO0koxocxkdooc:::cll::cdolddddoxxdoxxOXKXKKX0xd;.;,,x0xkKK0OOkxdxdlodlodoxxxkx;:occlk0O00xkxxOxkkxolddlllllllcllldollol:::....,lxxo;,;cdc:,';;.  ..      .:dKKKWMMMMMWXWMWNWMWXWN0koooooc;ldcccc:ll:;:c:cl,co::lcccccllc:cc::cl;:oc;::llc;:::lc:clc:cc:lcoolldolllldxooccOKx,,,co:ll;cc:dlcolllllll:clll:clcc:;:c::;;lcccl;':;,;::,,,''';;,,:;.,c;'''... .'..','.....:lcc;;..,.,;...,loc:c;;;:cll:;;:,.                           ..':;c;';''''.
..,:clddll;',..';:ollc:okollokooolc;'.;;'''....;c',;.,,':;.......';',cl;',,',......',cc;'...,clodoodllodxxdkkddkodkxkOxxOkO0KKK00Xxll';dddxO00Okc;xOx00kx,.'..,dx0XOkxddxolxOkk00Ok0Kxdkkodxdooxdoodoccc:;:codlxxloc.;xOkOxloxooodxxdooodooooododdodo:;,'':oc'.:cl;.   .'''..       'ccdkdxk0NWWWNWWNXKKKKK0XKkxddolddo:cllol:cc:cllllcc:clcc:;:lolcccc:,ll,:l:;lc;co:::lo:l:;ccolc:cllllclo;:xdccl,,;lolodll:,,,:;cdllc:;;:ccc::;:lc:;::cl;:c;:;;l:;;;;,;,:,',;,',;;,;:;,;:'';. . ...''.. ...,'.l:.'. .,....,,;lc,;;:c:::c,'.                        .....'','.,'',','....
..'coc:::;,;;;,cxdxOOkxxxdkxxOd:;,..'..,':c,;c,,;cdc:l:ll::olooccc;;l:;;;;cc'.',. .'.':looxkcdK0OOd:clcok0KKOxdllxxkkOOdlxdoO0KK0OOkxxkdOK00KXK0xdkdlllOK0Xkc:oddkooooc:xKNNNX0kdOK0kxkxxkdol::lloodOxxx:;;cxkOOkddl,,c:okoolcokOxxdodloxdooxddoxkxkdxkxooo:;l:. ';...   ....         ';:oxx:,oxox0KXKNMNKXNX0KXkxxooddd:;dococ:c:clc:cccolcooc,''cdc:lccccc:c::l:::;lc,cl:cxl.,::ll::;,c::;cc,clo:,c:;:;;:c::lc;;:;;:c::::c:cc:c::c,;lllc:::';c::,,c:,;:c:,;;;',ll,:;..,:,,,;;,clc:,'',;;,;.';;l;,,...  ....,,'':oc:l,',,','                   .. ...;,;loccocollo:coool:;,'
....''''::'',:l:codkkkOkO0OOOOkdoddd:,.....',..;,:lcxl:c::,,;cccll:;;;;,:;....';,cl'...;;cxdk0k0X0kkxoldO0xlc:;ld0K00dcldxllxlcclko,oxdxdxOK0OKNNOx0kxOxkO00o,cook0xoxl:odlxkc'cxkOKK00000K0xddodOOxo::oxk0xx0Oo,,;oxkOOkddxokdoodookxxxxxxxxkdxkdxxk0kxk00k00kk0kxx:..        .';,...   .''';,,ldxOxoxkko;oddKXNX000OkOKkOkdlcxoodoc:;:l:cc:c:'.;;;c::::c;:cccllcollolc:cc;;;;;:c:;lc,:c:;,:ccc:;c;;c:c::l;,,:c;oc,::;::;,c::::c:c:,coclc;:,,dool;ll;,',coxc....'',:',,.';::,'.....,cl:;::. .:clool'',..,' .. .':lcccc,,'..,dl'.               ..  ....;,..,,;;';c;loododoclocllllll
..;::docloc:'.;:;:cl:cdddcckkkkxddoclool::,.....,;'.,'::':;',:'    ..... .....'''';,';:lc:oxO0XNK0XKOOOkk0xc:lkkkOxllcodddodxdxo,cl,;clllodOKOOXNKNNKOdddllxddxcldx00xxkxxdlllcokKxldook0KXNO0KkxoclocldkkOxdxdocd0OxdlloxxkkO0xxdoc;cc:ccloxkkK0OXKOOKKKOl::cxKK00Ox0O:'.        .,::oxd:.   .,:cc:;ok00OkkKM0ccdlckKk;.;loocd0dco:cllllddc:lccllo;,clccoc::;c:;:;,:llc;:ccc;;::;:c:olc::lc:;:c:;:l:::cc:;;c::;,;,:l:::;:;::;:,,:loc::;;;',;::cc,,lool::;c;',,;oxc'..'';:::;,;;''.. ...,,;;'....  '::::,.';,. ....  ..:loolc;,,'..      ....'..;,,;,;'',;.,;::''...'..,;,;c::c:clc::,,clc
...;oodxdc:ccclcll:cool:okc,'. ;:;c,'coloxdoc;..'';,.';clodd; .'.'c;  ...''..'.,;,:::cldxdxkOK0OOk000KKXKXKOKKOkkkKXXKOxdolkxdOkO0kkddOOkx00kOKKOKXkkOkO0OxOOO0xxkkkxkK0xdodxOxdoccddcc:cool;cdOOk0klcoxxd:cocoOxodxxkkdxOOdl:lxxdxOOxkklloooc:lldkO00000odXX0l;loxO00kdxl,.         ;ookkllclc'     ....,;kNXWNK0KW0coOllkdlc:cllclooolol:cldooolol:lll:col;cl;c::lloccdxc',cc:c;;::c:cc;:ccc:;cccl;;cc:c;::cc;:l:,:cl::::ccclc;,lo,:l:;::'';;,;,,;;;:c;cdoc,,:,,;;,';,,;,::,..ldl:.   . ....    ','...,'':,  .... ...,',,,;;;,,::,'.       ..::;;,,ldoc:;..,,.,,';,:c;;,',.''.';',::c;;;..,;:
.:okOdlo::llll:loooclc:lc;odl,.... ...,ll:;ol:ll,';'   .;::;:ldo,',,,'''',::,:c;clclodoodOWNX0xkkxxOxx0XXNOdd0WNNWMMMNKOkkoxxolooxl:xdlx0OxdxONNNWWKKOxkdkxxOoxXOooOOkO0x0Kxodoll:,cdoddodl:ldl:oxdodoc'.,:colddldollldooodddkOdoxolodxooddolxxdxkxOKOKKO00OOOxk0kOOOOOdo:..         ';l0KKXXXKxc:,          .:KWNXNN0OOkdOxodloxdddcld::ccooldxd;cl:olcll::olod;:l;;;;;:;:ldccl:cc:cc:cc;:ll,;olccll::lc:;';:,;do:;;l:',clc:cldkd;',:l;.:c::ccll:,;:;:::;;llllc::',c,;c,',;:clc:..;'.             .';l:.  .       .''''. ',.;;,':;,;,';'..'.'..'.';:dl;;:clo::,.;:''..,..:lllc::'..  .,;,;,';;,,,
.;oolldl;;locdkxkkc:cll:;:clccoc;;::;c:;;..,:lcl:';;'..  ...co;cllxo:::ccc:,;cc:ccdxox0KNWNNWWMXKKkooxOK0OkkkkOkkXMNXNKKOoxO0kxOxxl''c:;odldOXNNNKXNXN00Kko:,;cdKKxkOlokxxkkxOOOxdkxodkdoxdddkxdxxolooodo:'..,lcoolxddkdodxkkxkklokoodookdoxdxOxoOkdxOOkkk00kOkxOKkkklcdoc:,.            ,cxkoOKkk0kkOx;.         'x0XWKKXOxkxddl;;cxdodlclll;;::llodcclcco:cd;'lxkd;,cc:;::::c;:c::lc,''llcoccccoo:;,;;'..','...',:l:,,,::;,,,;:c;;:c::::c;',oo:c:::;c:cc;:c;:l:;,;l:,',c,''.''':oo:.   ..              .;o;            .    .,:;',;,;;'........     .;oloo:;;;,,;:,;l;';'',.';:clo:::.... ...'.;::o,
..:o:;::,',lolol:;:lolcl;;cccoccolldxddd;..;,:l::clll;,::coll;coc:odl;:l::c;'..:okk0WNXNNNXWX0OkdoxxxOKKOOx:..,dk0NMNNWNNKdddlcldl:lokKOoc:;l0XXKKXXKK0xdoc;:lddO0Okll:,;lllooldddlodoxddodooookOKKkxxdloo;,:l:lodxldodxoodxOkxkOOkkkdxkddxoxxdOOkxxkkodxxxkdokOddOxclc:c'                ';ldOKKOdd:;d0Ox:.....   ..,okkKKOOkddllc::cllooclddclocllocclllc:llll::c:oxl,;oc:ccc::co::c::,';;,ckOOOd:.  ','..;:,;lcod:;cllc;:ll;';:;';oc;cc;;'',lxc;cl:cc:;:;cocclc;;:lc:;,:;..  . .,,'......            ....;c,       ......'.'',;,''....    .   .,.  .';:cl::c;;:;;'':c:;::'.;;clccc;:lc;. ......,;,c;
...''...     .:c:;;::cooll'',;cccc:.'odllllcoxkxl:,'.,cloldkxooood:okkOdc',l:cllo;:c;:;'..;::ddOMWWXNWXXKKNKXKkON0dl,'c:.;kKXNNNXWWNX0xl:,,,'codOkOKXXX00OOKO0KOOOddxddkxloxkxxOxd;.,cdooxooxxdkOxddxkxlod;cdooO0xxxddodooxxkOkxxoddddddoclxoxkdkkOKOkOxdddkxdkdxxxkkddxxkxxxlc:,;c,..             '...,cOWXXXOkl:oxolo;;cll:,;:::cccoooxxcdx:;coddllolc:cloxdlooolllc:clollccocllc::ol;;oocollclc;ll;,..lxkOOxdc';,;llc:,':cclllll:ll::cll;,ccldxo'..    ..co:cl,,;c;;;;::;cc;:c;,:;,c::c;',';,,'',,:. .    ...,.,lcccccoo:::;::;cclc;cc:'.. ...       ..  .';....,,';:..',',,,;,;;;;','';:,lllolocc:.'......',,;;
..';,...   ..  .:c,.'dkdccool:,::;:::ox:lkd:,;:dxol;'';ccodxOOxdddkxdo;:ll::,',:loxkklc, ,ooclddk00XNXKNNXXNNXWXXNKKKklcclc,;dKKNNNWNXXKOxc;. .,;cc:x0XXNNXX0ddOo:llldooOOOOOxO0xxx0K0kxO00OkxxxdxxkOxddkOkkkOkxxxdxkddxOOxxddkO0K0kxdlooddooooodxlcoddoxOxdkxdkxdxxoxdokxdooocloc;.                 .':;...,oONXNWXkxddocll;:;;lxxdOkdkxccloxxooccl;cdocxxc:llloodlclodlcllccocloodocod::::cdl;lol:;,,,'..     ..,cll;;cc:;,.,clllddccclc;:;::..okOK0l.   ...''::,::;:::::;co,.;lc:c:','.,clll:,;:'.....',',';:,;;;;;ccoxoddlll:;;,'',;';cl;,;:,.'.    ..... .'...,;;;:llc;........';;,::;cc,;;':c:llc:c:'''..'...',,;
..',,..'... .. .;c:;'.,loloccooc;,::;'.:looxkdlloodoc,;::okkO0kdxkxo;:ddldo;l:,lodxxddxc.'clld0KKXXNXNX0XX0XNXNXKKX0xkkoxxkKXKxodkKWWWWX0dxd;..   ..'c:oOXKXXXKkxxdoodxdlllxkookoxkk0OkxdkkxxxxkkxdxkdxkkOkO0kkOxOOxxOkO0OOX0OkOXO0OOKkkK0kxOOxO0kk0OxxkxkxO0xxkddkkoodccloxololll'.                  .,ccc;.cdoxkO0X00Ooxdclc:;,:lclllloxdollodxdol:locloloddoll:lldxooccoc:clool:;;cloc.....,cdxkxxo,.       ... . ..;l:;;:,.''.',,,;cll,lkc:;;:'';cdxo,.;'',;;:;c:;;;:,:oc:c;:c'''',,,...':cc;:;;,'''.   ,llldxoc:,..'',ll::ododlc:.';;;..,..,;,'...  ...','.',. ...'.'c:llll:,....''.',;;cc:c:c:,cc:llcc;..  ......,,;
...';:cc;,'.'. ...';,cc::'',cc,,:ldkko;:cc;.;:col;:lddoldxOKO00Oxxdddxxxc,cxxoll:;;:::lc::;:llo0KO0NXKNKKNXXNXXK00KK000KOOKkx0K0kxdoxONXNNNWNK0k;..      .;dO0XNX0KX0xkOdkOkxxOkkkldOxxkx00kodxddolc:,;:cc:::,;c:ccodxK000OkxolldxOO0N0kkxkxx0OOOO000K00OOOKXkxOkkxxxdxkdlddoxoooldolll:;;c;.      ..':c:. ...  ..;lkKN0k00kddooddddlllllollolldolxxdxdooccloloolddllo;:dcooc:cddcoKOxxc,,;:lc:.....l0NNK0Kxc;;::lxxdo:  ...,cl;:c;;cl;;c:,;:,:;:olclc;c:,;;;,;:c:';;,',;;ldcl:,:,;;';,,;,;::;:lclo:::;;;c:'''..:clcoxl;;ccc:;::lclc:odooc::c:lc,;..''.'.  ..  ......'' .......'.',,:lc:;. .;:;;,,;,;:ccolc:cc;cc;,'  ..... .''
.',;:,'.;:ll:c::;',;;...,'..:dolo;.',:c:ddoolcllxOdol:coodxkO000xkkkkkOkxoodol::'.;;;,;ll:'.. ...,,':kXXXXK0X0KXKNXKXxx0OO0OkOKNXKXKKO0koxKKXNWWXXXKOO0o........';cdO0OXNKK0OkOKkox0ox0xddlodc,,'';'... .                  ..cxxdolcokOK0kkk0X0ddxllxddddxkkkOOkxkkkOkOX0OOkxddkxdxdoodl:cdddddddl'.'':oddxo:cokOx;.       .;oxocoddllooodolddoolddll:',,',;;;,,;cldxdkkxddlcoodOdol:'.,;,,:lloxdoccllc::. ..'':oxkxxddOOOxoxolooxOo;:l:c:,,;:;,:;,:::c:;clc;;;lc,,cl,.::,;lc;,:::loxd:lc.,,.'.';,.;:;:::oodlcl;,,::;;;;c;,;ldxoldlol',:cc::;:ccl:'cl:clc' ';...            ....   ..    ....,,',' ...,c:c;;c;:::doll:c:;:,,.  ... ....
...',:cl:ldododxcokoc:ll;;cl;';ldo,,cc:clc,,:ooodocc:cdokKxodddOO0XKXXXXXKKKOkxoxd;:c;.    ,c:oo,''.    ..;;'d0OKKXNKXKkO0OkkdldxocdOOONXNX00kox0KWMMNXKKKKNKX0oc,;c,..;lxxdkdOX0000Oklldddlc:co:;. .                                 ....';ckK0KKOKNNXXXXNXk0Odxodkxdodkxkkxkdd0Okkxkx0KOkxOkollllllodc,.  ..,cxO0kolcxO0Ol,...,;,:cclol:codocllcc:dkxxodl'..             .';:loooddclooc:..      .,llolcll,.;. .        .clod;,;''.':lododo::cll;::',c:cc,cccddc:xdclloc';dkodxdkx:c:'''.';cc;;:cc::;:coo:lc;cc:l:lxoc..::;,..'.,;;;ckocc',:,';cc:;....;cccc,...   .              ......         ....,'',.....':c:clc:cllloocc:;;;'...     ...
....':ddd0kddlc;...;ddkOoodxddo:;;,,ccc;:,';:cdd:cl::lllllldl;cloxdxOOoOK00XXKXOxdlclo:'.      .ldoo:......       ;o0WXXNXK00XNOloooxxlo0KKXWNKXKK0kO0NMWNXWXKKK0kOxlolldddxoodxOOKXXK0NKOK0Oddo:ll:llo:                                        .,o0Oc',o0WWWMWNWWXKOxddxddoddlodocoddxOkkOdxxdxdddcloclc,,.      .,;ldoook0KNNX0dcldddololcllxdodcoddl:oO0kxxd:.                     'cdkocxl'.    .',,:looc::cc,.              'cl:;;',,,::;clc:cc;:c:;;cc:c:cclolooclxdlolldxO0Okkkxkd:c,  ..   ..':olllcc:;:::ccldoc;'',. .,'','',;c:cc;:c:c:..';,.,;;'....;;cc,.       .   .       ...... ....      ...',..'. ..',,cl:lllllclc:c;:c::,..       .
........  .;:ldxddl,...,;:ccccloooolcoocc::lccc;;cl:cdxdllc:cclc;lkxddx0OdoxkkO0OkddxllxkOxodl:ccl,.;:;c:,;;..',c,..    .,xKOO0OkO0Ok0OxocldxkKKKNNNNXNX0XKKKKNXKXN0KXkdloolc:oxko:lloxO0XNXKOXK0XXXOoocclclc;.    .                                     'xd,,:;xWMN0k0WKOXX0OdOxoloocddxllddxOkkxoxkxxddo:,,..  ... ..'',;..',oxkKX0K0kdccooddddlododl:cok0KXNX0Ok0kc.             ....,:,;oxk0Kkll:.';,:c:lol:ldxolc;'.  .'.';,,'';''';;,;c:coccc::lcll:l::ll:cooccoxkkl:llc:::ccoxOXKKKOxo:';;,';lol:;,'..,;ccllll:llcol:c:,:,,:..   .;:::;codl:coc:lo:;ll''..'::,,c:;:'. ...'.....,;'...........  .'''..'...........'..'''',',cll:c:;:cc,;c,;cl:.  ....'
.',:ccoxx:::'',',cclldkdl:;;ldxxkxxkxocclldlclol::ll;'.,c:ldxdoo:,..;x0kkOdl:;;:;,',lolc'...':loo,':;,:cccdO0dxc,clooloo:.   ,;:dkK0xxocllccdxcxOO00kOO0XWNNMMNNN0KXK0kdxOkOxxkkloxoodkO0KXNMK0Kkkk0O0XXXXXkdkxOKOxkkookxxd;'.                                 .ck0dcodxXWKkdlx0O0OOklolccldk0kxk0kxxddddolcolldkc.....',;,....    .,,,:loxkxdxxooc::lxxool;,cOXXWWWWNNX0ko:.     .,;:c;....':xOx;',;ldkxc:lcdxdl;;;',llddldol:,:c:clclocc:;cccllc;cl:;;::,lo;llll,,;;;oc,llodcc:cooc,:clodxOkxxkxxx:,,',,,;;,:;';:cooxxkk00xkxlol:;::lc;:,.. ..;:::;clxkc:lxolccooccl::;;lc:cc'':;,;:;:'...;,,'',',:::,'..    ... ........ ......',....'.,c::;:lcl:,,'...''.......
..      .ckk0xoxdxoldc;cdddoxxxkdccokKOkOxoddoc;looc:lc;'',cc',:okkOkdl;;;,ldx0OxOxo:.  .,::;clc;..',;'',..,;,;ldxOX00KOdd0XKKdc:'...;ooxkxxOxoooc;'.'::xXXKKX0KWNNWMNKXNXNXO0KOkkxxOXKklllcloddxOX0KWKKXOKkckX0OkkkxOOoloxod0xoxkkl,'.',                              .,d0XX0KXKXX0kOkooxxxxdl::ook0xxdO000kkdddllllc:::llll;;:;;.,,'.   .,:ll;ccckkddxo:,'.,:odxxo:;lKWMMMMWNXNXo.    .;ld0Odd;    .;;,;:::c;,lolccodolllc'';lo;:lddlol:::lllcl::c::cc;lo:co:;;clcxo''',,',:c;,. ''.'..'cdo:cllooollcclloolclodll::l:'.';;lo:cddxxdcc;:ollc:;,;c;';,..'. .....,;:odxlodloloxc;colol:,. .'clclcc:,'.:;,'':cc;.;c;c; ...'..'................''''. ...,,;,:;;c:,',. ....  .'.
....  .',c:,;':dddddl:,'';'';;;;,..:dOxkOdoooo:cdlddoddc,,,,;ldddodxd:''',ccxxodl,....,;:ccclcclcc:,c,.;;'  ;odkKXK0XK0NWK000xl;;,;::llcddoOOxocllccoxxOXNKKWMX0NNXKOOkdO0Oxloxdo::k0OOkkxlox0KxOKxxOdlkkOXOxkO0OOkxkkxkk;..lkkkxxx,                .            ...,:::o0KKKKWNXXNKkxoodollld::l:cc:';xKK0OxkOkxocclccllllll::ol;,:oo;;;,;::cc:c:o0kddcoxdoc;;:lc:c;.;xXWWNNMWXX0:.,,,;lxxokkdol:,,;;;.''';:clloolol::lcldl:;lOxc;;lcclcldllo;cloc;c:;::clxkxlcdxo:cc,:looccoc::,.     ..';lx0OO0kkklllc;;ccoxxxdo::cllldxdc;;,..;;;c:'.,;;cc;;:;,'.              .lkddc;:..:;oddkxdl;.',lllolcl;.;::c:c:clccc;cc,,. .'................... ...'.........;'',',;'.... .  ...
.'...'...;:ll:;::lxkxkxdc.         ..'okOOOxodlc,''.,cokkdddldkdddxl:;'',:lcdxl::l:....,loooxdooxOOxo;::,c,,:::,;d00KKNNKNNNWNK0kkkoc::,.,;'.;dxxd:''',cokOKXNNXWWXNK0KxxddodkdkOooxOkx0K0KX0kodx0N0xKXkkkdcl0XkoxOK0kOxOWNKK0d, .cdood:.                          .'cld0X0kxOOk00OKXNXOkxxollc:;,ol:lc:c;;:dkxkxxoolxdldolxolololoxlc:;:clcloooooloxdodoccoccdoolcc,',''.,odOOO0ddooddoclool:cdccdl;:::::l:lococcxkxdoxkdcll,;cldookdclclllo,cOocc;okxkkxl;cloxdldc;lc;,.......';:col:.  .'..;:;;;;:dxoxdodc,,,,;ll:clc:,,cc'',,;'','',clc:,'..'::cdo:;.               ,O0xkxc,..'.';ckdll;:;,cclccc;;;coclc::cccc:clc:;..,...''...'''.'.......... ....'....''.''......'....  ',
..  .clcc:.,c:colc;'..;,:xxoxd.        .;ldxOOkxodl,;:;,..llodollccccc:..      .',;,....  .;:lddc:xdcxxoxllool:;,,..:lcoc,:xNMNNMNNMWKxxxolc:;;,..,oOo.   .,ldkKKKNWWXNNKKxx0kolddxko:lldx0NNWNK0kdx0KO0NkkK0kO0dlodkkxk0doocoONNNN0Ox;coko.                         .,;,cdk000KK0xdccdookkkK0kOKKkokkoc:ccloodxdddooooxoclcclo:':lcclcclllcc::cllldocl::llldoldllllllocdo;;;..,;',loc:;cclolc,:llccdo:,co:;,;c:cc:oc:ll::::codolc::ccldoodo:coooxdol:c;,cxkx0Okdcclcldlll,;c;c:'..,;:col:cl;.....'cl,..  .,c;;::;:cxxcldxxddlc,.  .::,clccl:,,cc,,...ckOxkk;                ,looc;;,',;c:.':lodl,;c,;ccc:;:cloolol:c::clccc;;;,;,';;,;,.''''''............'..'......'. ...............
...';:c;;;,:;;oolll,',.        ..''.    ..,;'',ckOkxodxkkodl'..;ol'';,;;cl,..  .     .';c;::c:;;;coxkxkookddxldoll;.  ''.:c::c:;:dNMNNNXWWXX0Oxol::oxdclx:;, .,:coxOKNWNKX0x0XN0O0Oxc;cxkoclk0NNNWNWXxdookKX0O0xd0OxOOOKXXOokxdxkXOcck0KNXKOcokc.                      ..;lkKOkxdk0NX00OK0oxxcckxdkOddxO0xdkoldxxxkOxodddooloko:cc:;:c:cdollodlcdolooooolddldocooooolloooldo:;lxo::codl:co::odlccoxolc:lololc::l:;::l::olddcc::::oxkdllcdoodddodxlclcllol;c:;:coolooc;:c:;;clc',c:::cc..,:::;:ccccoo;,:lcll,'. .:;co;;::c:clcolll;...    .',;:c,.';.':;'...:OKK0KO'            ..,loodc;..    'c'';;ccc:;;:lcll;;;lllccc::;,:clc:;,..;:c;;;'';:.';;,''''..'..... .......'........ ....'......
..''..''';c:;:;:;,c::dd;.                    .';cdxlcloolc::llc;.....,cc'...;ldo:,.....  .';,,:;:,.'.   ..;c;,;lo:;cl'...   .. .....;clkOKWNNWWWNKK0Kx:lO0k0Xkxo;..,cloxOKNXOXkxOx0XXXXX0Oxxkk0XX0KWMMWWWNNOxkdOXXXOk0KOOxkKNNXNNN0ookXOx00000KWKK0xdo:..''''':l;.       .'coddOK0OOOXXxk00NXKXNKkdlcc;:okOkdo:ddcl:cxdddllldkddoxdodoooxolollccdxc,locolclodol:ooloocccloolooclccc:cl:looolclc;;:ooolooooloocodolcl;':,;ccc:codoc;,;coc;lx::o;:o:clc:cclxlclcol:cclo:cdxkxoll:;::;lo:,,;:cc:,,,,;;;colododoc:c:,'.,::,ll:lldOkkdc;:'       ..    .,;'.   .'.,'  ..:ood0O:'..''.  .   ...cxddxl'....,,;,.'',;::::cl;;cccloollc:lc:;;ldooc,''.;lo::c;,;,;::''..'.','..... ......'....... ........'...
';,,,':,,;,;'.,cl::l;.c,             .,,...':ldkxdxdoooccdc,,,..  ..  .;llo;,dl:;,:;..;. ....              ..'l:;;'..                 .ckK00NMMN0OKXKXx,lKXK0koolcdkxOKOOOOKxcdxxkxkKXXK0O0K00NMWXNMWXNNNWNNdokdOOooO0KOxxxk0NNXXKNXdlxxoxkkkOkkOXNXKd;.   .';ldOxoc. .;:cxKKkxO0KKkkk0KkxO0O0KOkkxooocolo0kdkOddo:c::odxddkkxolddooolcooccdxlolccoc:ll:cloolooclclooc:ol;cocclclc:;;,,:ooldcld:clcclxlldkxod:,cdl:lo::c;',c:;cll,.,','....,;'.'coc::;''cxklcccxxxoloodokOOxo:odccl;od;c::c:,::,,'.,::llolodoolcl;;c;cooooc:loxxl:;''.      .:d: ...;:'...'''','.     ..'.':;;:;''.. .. ...;,;oc:;''.,;:cccc;,c:;cdolc:c::lccl:c::l:,;clllc:c;,:c;clcc;;:;,,';''..,'''.''..'..'.'............'..',...
....''';;'::'..   ':clodoc:c:'           .::;:;:cooldoc:cc:;:lc,;'    ...'. ..,;,:cldoco:;'                      .';,..                     .:OXKdxXXOx0KK0xx0OkOx00kKNNKNWNNX0kxllll00xO0k00kOKNWWWWMMWNWMWWWMMMNKxo00xc:dOOdlodkx0NNN0xOkdoocldook0K00KOOk,...'coxdxxddKKdlxOkxO0K00X0K00KOOOxxOOO0Odoxxxo;oxxdlddO0kloolo;,:dkkxxxlokkl:coccocoxoododolldocodllollllloc;llodc:lollo:lolo:;;;ldxdllc:cc,;clccdddolccoccccoo:;c;;lllc;;,,:;:c::;;;..';ccc:;locxOkxooollclocdOkxOkc;:cc:',c::,';:l;'',;c:',;,,coclo:c::odlo:':coo,.;xl;.    .,,'...';;c,',.',''..'.',',.....',,;'.''',,'...,'.;;',;,;;,;;,..':lloooo::;,oxxdoooloocc:;;cloooo,;;;ccl:c:cc:c:ll:cl:;;;'.','.,;,'...',.',....'.....  .........
.''',;,... .'...   .,;,;dxokkoo:c:.     .':;,::;;';::cdxdoooldxdl:c'. ......  .......cc';:....                                                ..:xKXKkodkddO0K0KOO0:.,cOK0NMMMNXNXKo;ccoxKNx:cddd0NMMMMMMMMMMMMNNMMNNMXxdOOKxllokdxKXKKXNNKKOkOolxxloc..;oOxloo;.,;,..oKKxodoxkklcdx0000O0O0KKO0XWNxcoxxOxdxoddoc:dccoloxoododdodlclo,;odoc:dxkdclc:cclxxxdc:ddcoc::loldxdloc:odollll::loll::l;;:clllxxclllloo:cololcldolclxdx0xll;:l::looo::;;;''clcc:,.''..':loxkoollodxlllcoOOxxc,'co;;...'',:lc,,;;lccdoc:'.,:;;,cl::,..'cclkl::;cc,cc'..';:clxxo:.''.;:cc;,,;,;,...'',:,...ol:c;;;''',;:;'',,.,;;:;,lc..;'.:;,,,::cocll:coxxkkxxdoodoocll:clxlllcc:cc::cc;:;:llcloc;,;'',','',,'.;,,;''''',,........'. .....
....,,''....     .    .',;';:,:llc:cdc:o:,,cc:loc;,... .,:;:oxkK0O0kxko:loccol;,'',;;::..  ..                                                     .;lkkxx0klkkkO0KO0K0koc;,ldkXMMMWWWXkl,.,d0OOXkdxll0NWMMMMNXWMNNWNNNNMMNXWXO00OKkdkOX00NXNNXXKxxddkk0KKx;..dxxxodl:;:odl::xKK00OOdcll:dk0Ok0OkkOkO0OOkxllllloloollldooxdooollllodllodkxdl:lkdcdlddoo:collxxxxlodloxlccldoooldoocll;cllcoo::lddoxo...,;clloxocdkocoloollll:lol:odloko:clooxxooolll;'.;;';,,::..;c:::::ll:;lxdxdldddoloc... .',:oo::;.co,..,,,;,;,.   .;c;..';;:,...',::cc;;:c,,;,lddoooc;lc,l:.,;,,,;cd;.    .;c;,,,;:,'::,'...',,.;:;cl;;ccollo:;;:::cccc:c;;l:;cooddx0xkxooxdoxOxol;c::llclc;::lccc:ccc:col:::;:;,,,;,;:';:,::,,;;',''.....'.    ...
..';,',,'.''...               .'..,,..,:;ldxdxXKddlcc:c,...  .lc:;,;'.'::,;,',ckxddc;::;... ..,,..                                                          ,::0K0Oxko:dkokOkOOxOklloldOOXMMNNWx.  .'codoodooddXMMMMXNMMMMNNWMMMMMMNXXXOc;dO0NNK00KXK0OkdlxkkXN00kkc .oXKxxolc..lK0kk0K0kkxddc:ldxkKOkOkOOddkddxOKxo00xxdlclolcloxodocooxkdooc:olldololoc;clclo:coxkddldxolllddldc,oxdooxdooooolcccoolllccodoc;:lcccloxxodoccoododocccloxxddlolllllodooloddo:;;c:,::,':llk0Okxo:oxllclxdxkddo;',;,.....:oolc.',';'...',...       .,,..''cd;,l;;cc:lol:od;cxkxloo:'  . ,oo::;,,;::l;'.';,cl::;;;:o::c,,';:,,,;lc;... .';;c::clolcc;coloc;xkdkkkkddddkxxkdxooddxkkooc;;::lo;ccccclcclllccc;lo;;:,,;;,;:;:llclc;;::,,;;'.'.......   
.,,::;lolloccdl:;;:.                .,cc::,cdkxxO0O0OOkl;.;;;c:...;:lo:;,.'.  .     ..,'.     .'.    ..                      .                                    'o::Ok0XKN0kOkxkO00kx0OdoccodxOKWMMNOddxdlxdlc;clxdkNMWNWNKNMMMMMMMMWWWNNWMKdlxKNNX0koxOO0xxd,.'l0NKkxdOk;:odOOkxxdlx0OxooOX0OOOOOxk0kO0KXX000OkkkxxxkOOOOkoodoolxl:oxlldollcoxdlddccdl:lkkdl;:llclodooxxolllllooloodddoclxoodoloddolccodooo::oxoc;......cx0Okkxodxdooddxdldo:::coocokkxdxxkkxdollolllllcc,.;oxxdloc;lloolcod:;ll;:;:cc:c:lc'cc..''......  ...  ',.',,::,;co,,occdololloolc:coxOKK0kxc. ..;ccdo,...'. ......':cccol,':,,c,;;,,..;oxdc... ....'.  .'';:',...  .':xKK0K0Oxkkodxxxollloldxdxocc:;:c;cc;cclllxOxl.,dl;;,,,',;;c:cdlolllcl:cc;,,;,,'..'.   
....'.'clllldocll:;ol'',',;:.  ..             ,cc::lldOOKXXXNKKN0kddxddxdlodololcdolc.....,'..   .   ..;oc.                                     .                      ..;,,llldxx0KXXKX0KNNXNW0olxo;:c;,:oOWMMMMMWKOxdl;c:clclONWMMMWNNMWNWNXMMNNNXKXK0OOO00OxoodclOxo00ocoddoldxkOOKXN0dk0xcoxkKNKko:dkxkloOOOO0kxkxxxOkx00kOxodxkxxkdlldddddllldxocdllOoclddllol:lddxdooxdlodddooxllxo:;looxo',okxlol:lxo;;loll::llccoxXWKd' .,''':ldOxc;:dOkdxkllxdoodlloooooo;'..';cc,.;olcl::c;'.'';,;:',:lxxxdc;;;'',,''':dolo;,c:;:;,'.....',;:;;c;.;c:::,cc';clo;,,,;,::;cc;;'.';:cllll;'. ...,;oo'...'''.,:.  .';,,::;:;''';c....;'.';:;,'.'..''. ....'';;;.      ,kkkKK00K0Okxdxxdxdllllldkxdollc:cc:clllcldddlcc:c:,'''....',:cllclodlodolc:;;;;;,'''.
.':odl;:llc,',,':c;;..',:c;  ''       ',..'::.,lxdoodkOKNXOxxOxxxddcldxxxxkOxclloxxloxkdoooooc. .' .'.  ..':,.                             .  . ';cxl:;;'.            ...;ccl:' ..;,.'lxONM0kXNNWXKkldxdxl..,oXMMMMMWNXOc;,:xxdl:dxxKWWMMMMMWKKNWMMMMWWNWXKXX0xddclkkxxoloxkk0KOO0OOkO0KXX00KxkklkkdxOOdoc::;,,oO0XOxxxOdxkxOkkkk0kddldkkkkoodxxdxxdldkoldddkolxdodxdccdxxdooccc:ldlcodol:od::ooodllcooc:lcdoodccdlldoldl;:ok0Oooolodo,.:odkxc:ldll:,dx::dkoccccclccdc...',:c,',llcdddkxOxdxo::,',;;loll:cccccl;,cc,ldcllllo;;o:coc:cc:cc;''cl;;.. .'cl;,clll:,';;;;:c;;:'.',cl;;;;:'',...        .'';,;..';'.'... .,;,..'.''.,:;,,':c'.cocc,.   ..'';:c,. .',:okxkOO0KKOkkkOxxkkkxooollllodxxc;cl:cllllddlollcc:co:cl'...',,;c;:::ldollllc:cclc:,.'.
.',;,'lc,:l;..,,'...''..'';;'.       .;:lddlllc:;;:dXNOkxo:''.,co;',;:loccoolcc:',cdkkxx0OOko;;;:c'... ...,.....                         ..  ..  .'cc;cclc'.            .......       .,ldcoKK0kKMMMXkkOOxclxdxl:ONWX0XN0XNOll0N0d:d0ox0kkkkOkOKXNWNKXK0KKKXXKkdl:'.';,;:;,;:dklokxxdo0OOKKKOx00ok00NX0kxxdxx;.;lld0xddcokOk0kxxxxkdokdooodxllodlcccoloocldool:kOdddllloc:doclcllllcloll:clooooloooddok0Ol..:lddoll;;dccocodoccdolllclldo,:::::coxdcodlccdddollcllokxxddocddxkkOxcc::dxlkKKX00ko' .,,';ododdxdcc:::':c;:ooolcc::cc,;:::,.     ','.  .. .;;;;looolccc;c:';:;cl:coodllxkkolc:oc'.      .;co;,;'..,'.   . .;,:.......;ol:':c;:lxooo;'.'.';;c:ldl:cdxxkxxOkxkxk0OkK0kxkxoddxkxolooloddolloc;::;clllclolccllcc;';;,;:c;;:;:c:,;:::c:;;::c:.,'
.''...   .'.... .,,. ..  ..'..'.       .ckkxlcc,':'  .,ol:,'..';ldk0dcldOO00OOxoclc''':odkOOkkd;,';:,::,;;''....                          ...:,      ;dooloxd:.                          ,xOOkdxkdoxXMNNWWX0occkK0XOkxc:dkxOKWMXkONXo;dOOdkOdxxkxlldON0dk000kxk0XX0kxdcc:...',,;ll;cdoddooOKKKkkkxkKkxOKKOkko:ll,':ldkkkxdxxxk0xxxdk0kxxlcododxxkooxlddclddoc:lolc;cxdlolodxdlldoldocxxccloollooooodolol:dkkollloooxxl;..;clooldoloodolcloc:coolccddclodo:;cdoooocodok000xl:lloOOd:loccodxOOkkoodll:. .;collol;'.'.  .',,,'..,c::dl;.  .;:.     .,;. .;,.  ....'cxdoooo:;c:,;::cccldxl:lxxdolodxol:'.;,',.,::;,:,....         ';..;dc,''cccl:,,c:':;,,;:,'. ..;ol:coodOxdkxdkdoxddkkOOxxxdooxkxkOdoo:cddxkdoc:::::;,;,;:::cc;;;,;cc:c;;lc;;c;,'';;;,;'.,.,;.
.,,''''..   ..     .''.   ......,,     .'',:lc:c'  .''.      .':clxKXXKOKOkOkkdkd:;:;'...'.,:;ccdlcl,.'c;''..'.                                   .       .,.;ollo:.       .              .,':xddoox0OdoxNNXNX0Ol;:dK0o::;.. 'kXXWXXWWNWNc;l;lx0OodxOkdkkk0kOXX0kxdxOOKKOkO0Kxlc;:oldo;,;:;,cxdxxkXOk00OKKOO0Kdclc:odooldOOKX0OOdoocccoox0KKxc,cdo:;:lxxooxdodo:lodxxddddxooc:dxdoxkl:llldc:xoclllxoldxoddldxoldlcllllok0Ko,,,:ododxddlcdolccl::lccolloldolcclc:okdllooodoododooodxoxxoooxdxOooxxoclcdkxdodxxdc;..   ,. '...',c;....:;ll;,,',lc,'.;,,c;...:xo,.       ;xxoc:,';,;:;:col:;;cdlcdl,..;:',;;,...;,.:,;clc,;...      ...''..::;:ll,,';doc::;''..,c;..',::::cl:lddodxxkxodkddoooldddxxddkOOkxdl:::ckkx0Oxxooc:;....',;;;'...''cdodxococ;,,',;.,,.,..:,
.',;;,',.   ..     .       .  .:xc,'.''.  .',cc::...;,         .''..,;oOkkOKK00xdkO000o.  .  ...... . .......'.   ..                                                .'cc.........            .,,'ldc'',dKOO0OKWWX0kookKXWMMNo','    'xX0odKKKWWK0l,dk0N0KX0xdllxk0XKOK00KOkdoxxdokOdxoolcldxxdlcccodlddoOxx0KK0K00xdxccooodol:clxKXKKOxllolloo::xxoolxOOxxkxdo:cdodxxd;,xxdxcddodool:cooddodc;oxlldlolodolcdooddxdooooxdllolcollool;:ollxo:loc:loddo:llcc:;;::oxddox0Okd,'...:xkxkoc:lloxcclcdolddol:od;:oldxooxccl:cc,.';:ll:cc,,;lcoo,..cOc....:lccodl:cooc:cxxxd;     .'';llc;.''.:,'c:;cdolc;,ldlc,. . .',co,.....',;cc:;',,,:...'...;c:'.,c;....,;;;c,.;ol;;'.;oc;;:oc:lcc;;oooloodkkddO0ddxclolodododkololccc,,loxk0KO0Oxol,...,:::;.    ';lddxkxooc::,;;;;:;,',,
...':ol;.       ..             .'''cd;',....,::,...';.'cl,     ..';:c..':lxxxO0XKK0xl;:ol:;. ..                                                     ...       .          .;,  .;c,           ....;;l:;loxddKN0XWNXW0d:'cKN0OXX0XNXNd.  ',ck0KNNOkNNKx;lOKXNXKKOkkxxkO00O0NNNN0Okdolllodolkxccolx0odkdkxdokxoO0x0XOxdxOdoOxdOkxkxdolcckOOKK00OOkO0kdoxl:llkK00Oxxdolllokoclclccod:oocccclo:clllcododookxdxoodlooooododolldllxdoddxc:oodc:cddcddcldlol,;llc:;'.;::ckKkolllxxlcl;'''cdlldd;,,,c;';;:ooclccc:oxodxxdolclooc;loll:;ox:...::co::::,.,,:;...,,':lc:ldolc:cc:oxo;'',';:,::cl;';, .::oo:;;cool:od:;,cc;.,lc;,;:,'';odccoc,:llll,',....,lllc;;::'...',,::..cxold;'ccloooldool:::ododolcoocdkxxkOxxlcdoddoxdldoll:;,,.:clxdxOK0xdc;,';;:,.    ...:c:oolddooc:cc:l:;;:c
...c, .'.                  . ... .;:c;co,.,.....   .:;:dc::'.....,:dxddccxdddokxx0000xxd::,.                                                                    ..   ..   ... ..:lc.           ':,:oc:o:...';l0MN0KOdkxldkkOkolloOXXWXdlodxkKXKX0OOkkkxd0WWXXXK0KOodOXOx0O0XXXNNKKKOXXK0dddokxdooodkxkOOxdoldxkkOkOkd0OdxkkOkxxOO0XX0OOxxO00KKOKKkkodklokc,lddkdxdod:;oxdxddclxoocoocollllolcol,:ldoldlloodoooccdo;lxoodxolodxodxxoxo,ldcldlxdldocoxxolclc..ccldlcl::l:;;lxxkkkd;:ollclldOocldklllcolloloolodllooc;;;:cc;,,lol;'.:l;..',',',:,'....'.     .,;;:ccoolcll,,oo:,.,lxo,,.;c;;,'..,looc;,,ddodo:',:cc,.;cdoc:,,,;:c:';llcc;;c:,c;.',cloddol:';:;'...';;..;ol;ldc;;codxddxdood:;llcoooddolodccoddxxkdodookxkxdddl;,..,,:;cooxOxxxoc::',,..'''..,,'.',,:coocc::cllccl
.'. . .,.                 .,;..,,:cldc...         .'cddokxc:llo:;lO0xddddl;:c::loodxd;..                                                ...     .,,'..                        ,cc,.          .  . .lodllc.'..xNNXKOo'.;dkOOOxdloo;xKKX0ko:::o0NMMNNWXxddxxkk0KKXXXK0OKWWNXXWMWKXNXXNN00K0OOOxldkdok0xdxkOdokx00dlxkxkO0OOOxokxoooOKO0K0OKKKKKKX0KKO0xlxdoll;:lcloxdxx;;odc:c:ccoodxccol::codlclloxddoldlldolloxo:ooldoxklcllcloollxkdc;cllolcc;',:,.:l:oo,.'cxxxko:;;c:;lcx0OOc';c::c:::clldOxloc;,'::,.',;;'';cc:....:;,,:c::::;',,''''',;,,;,. .,';,''.. .,.':;,c:lllocc::;,cllldl;;'.;,',..,lol,,;;od:::;;:c:c:,col:;;:ll:c:;c;:odd:;,..',;;:c:ododdo:,;,,;'..''.;,ckc:cclllloddoddolododc';:cooooollccllllddlddcclokxxxkxxcc:,;,;c;,ol:lllllc,;:,;:',;,'......';:'cl;,,,ccl
.'..     ';,.         ..',',.,:;:,'.,;,.          .,:lxdldxxxoloddlclxkdoodo:',:;,,;:cdo...                                             ;l;.....   ,o:,.   ',.                 'okO:                 .cc;::;:lcxOxdO0kc;okkkKKkxdl,.:OK0doxc,,,cxKWMMNNMXKKxoollolloKNKk0NNNMMWNNXXNXK0X00NNNXX0OOO0O00O0OOOOOdokO0koddxOkxddkxkxddkdddodl:lo0XKNXXNXNKOkdxkxxxxxdddkxxklldxdloolllc:dodocooooldolloxdkdlxxdoooodxxxkdxxloxdddxolooxdlcdddxlod:....';::::cocclddkdcl:',cxOkd;cOxol,;'''....',,;;;',;..cloc,,,'''.;oc',;;.';':c;,,;;:c,'.,,':,...'.    'll;,.....'ll,::,'.'c;'::,,ddoccd:'..'',,'';cloo:,cc'.,:c',.  ..,c,''.,;::....,',;':l. ..,:coo:odoxoddo:;odl:.,:;c:coodllddoddlooooododoool:;::llcooccccooccolodccocllcldddxkool;:c:;c,.:;',''',:'';'.;,,:;,..'''.,;,:,,'';;
..':...        .:c'..''  ..'',cc::c:;,'..         ....;,';ldclddolc:c,... .:cdkccxo;;.';,,.,ll:..   ...                                     .';:o:,;'..,;;:'   ':col'.''             ,xdxkc.              ',''.,oc,,lxkd..:lxddO000XkxKK0OKWWOOOoooxKKKNXKWMMMMNNMXkkocc. .::';kXNNXWMMMNXKKKKKOONNXXK0KKOXK0XKOKNKK0XN0KX0000OOOOO0O0K0kOOol:.     .:d0X0K00KOxxOOOdlOOxkxxxkOxodccollddcc:lddooollooolllolcoooxdlldxxdxO0kdxxxxxxdxO0Okdoxxxkxdccll:';c:;clxxlc::;:;;;..  ':,lkkOolkxc;..      .;:;::'. .',;:c:':l;.,ccdl,:lc;'ccc::c:::llc;';do'''':'...  .,;:,';lc.'l:,:l;'''',::;,..;dkdoc:,'::,.......',;,....:l;'.  .'..  ....   ..  ...  ';'.....';;cl:;cxko::xdodccddllocccoodxoxOkkxdoocodolldoolcc;:lccc:lllcllcccclllcll:cdddxdollllccl:,;,''. .,';;''.;:;:cl:;;;,,,:,,;,,..'
.'';,.....'.      .',';c,;;.clc:;;,,;,'...          .;lo:;;'.cxdloxk0l.       ,doldddxdl;,;....'cc;..;;cc.',.                               .';cccc'.,,,...,ll:..';c;.......           .loccl:.              ';.,cccdl''dOc;.,cloccxOOKKxkOxxkXN0O0OdocoOXWWWXNMNNNX0KKdxocdl:cc,'cxoxK0XNXWWXXXKNK0XKO0OkOKX0KN0XNKKKOO0XXKOOOkkONMMMMNNNNN0kkodl.       'dKX00OKNWXX0OOdxkxxooxxxOk:cdxdddc:coddccdlldlolcodlodlddokkodxdkxdOkdOxokO0kxddoccdxodxc;..c;,::;..,;lo;  .         .,;odlxO0Oxc.        .':,,;. ..;l:,,,.,ldc,lllccldo,'::oc.:o;:ol;:lcloc:cl:::,.  . .. .oldx:....;:..;,'cl;:;:lllllc:cloldo.    .' .....'.      .'.   ';..... .        .',;c:'..'.....',:ldxxdoodokxoocodolododxOkk0kkocl:odll:lxxl:c::ccccllcllc:cc:lc:c;;::oloodocc:clcll:,.'',;;;,;;,;:cclc:c:ccccllclc;;'.
"
}