-- Run with native runghc -isrc. Geometry has one owner: Site.HollowGeometry.
module Main (main) where

import Data.Bits ((.&.), (.|.), shiftL, shiftR, testBit)
import System.Directory (createDirectoryIfMissing)
import Site.HollowGeometry (hollowVertices, hollowVertexCount)

main :: IO ()
main = do
  let vertices = chunks 7 hollowVertices
      payload = base64 (packBytes (concatMap vertexBits vertices))
      output = "generated/Site/Widgets/HollowGeometry.hs"
  if length vertices /= hollowVertexCount
    then error "Hollow vertex count disagrees with geometry"
    else pure ()
  createDirectoryIfMissing True "generated/Site/Widgets"
  writeFile output $ unlines
    [ "-- Generated by scripts/hollow/Generate.hs from Site.HollowGeometry."
    , "{-# LANGUAGE OverloadedStrings #-}"
    , "module Site.Widgets.HollowGeometry (hollowGeometryText) where"
    , "import Miso.String (MisoString)"
    , "hollowGeometryText :: MisoString"
    , "hollowGeometryText = " ++ show payload
    ]
  putStrLn ("hollow: packed " ++ show hollowVertexCount ++ " vertices")

-- Six signed milli-unit coordinates/normals, then an unsigned region id.
vertexBits :: [Double] -> [Bool]
vertexBits [x, y, z, nx, ny, nz, region] =
  concatMap coordinate [x, y, z, nx, ny, nz] ++ bits 3 regionId
  where
    coordinate value =
      let quantized = round (value * 1000) :: Int
      in if quantized < -1024 || quantized > 1023
           then error "Hollow coordinate exceeds packed range"
           else bits 11 (quantized + 1024)
    regionId = round region :: Int
    bits width value
      | value < 0 || value >= 2 ^ width = error "Hollow field exceeds packed range"
      | otherwise = map (testBit value) [0 .. width - 1]
vertexBits _ = error "Incomplete hollow vertex"

packBytes :: [Bool] -> [Int]
packBytes = map pack . chunks 8
  where
    pack values = sum [shiftL 1 offset | (offset, True) <- zip [0..] values]

base64 :: [Int] -> String
base64 [] = []
base64 [a] = [digit (a `shiftR` 2), digit ((a .&. 3) `shiftL` 4), '=', '=']
base64 [a,b] =
  [ digit (a `shiftR` 2)
  , digit (((a .&. 3) `shiftL` 4) .|. (b `shiftR` 4))
  , digit ((b .&. 15) `shiftL` 2), '='
  ]
base64 (a:b:c:rest) =
  digit (a `shiftR` 2)
  : digit (((a .&. 3) `shiftL` 4) .|. (b `shiftR` 4))
  : digit (((b .&. 15) `shiftL` 2) .|. (c `shiftR` 6))
  : digit (c .&. 63)
  : base64 rest

digit :: Int -> Char
digit index = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/" !! index

chunks :: Int -> [a] -> [[a]]
chunks _ [] = []
chunks size values = take size values : chunks size (drop size values)
