// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Internal__Dust_Syntax$Dust = require("@fahmiirsyadk/dust/src/Syntax/Internal__Dust_Syntax.js");

function main(post) {
  return Curry._2(Internal__Dust_Syntax$Dust.Html.Elements.html, /* [] */0, {
              hd: Curry._2(Internal__Dust_Syntax$Dust.Html.Elements.head, /* [] */0, {
                    hd: Curry._2(Internal__Dust_Syntax$Dust.Html.Elements.link, {
                          hd: Curry._1(Internal__Dust_Syntax$Dust.Html.Properties.rel__link, "Stylesheet"),
                          tl: {
                            hd: Curry._1(Internal__Dust_Syntax$Dust.Html.Properties.href, "/assets/css/styles.css"),
                            tl: /* [] */0
                          }
                        }, /* [] */0),
                    tl: {
                      hd: Curry._2(Internal__Dust_Syntax$Dust.Html.Elements.title, /* [] */0, Curry._1(Internal__Dust_Syntax$Dust.Html.Elements.text, post.data.title)),
                      tl: /* [] */0
                    }
                  }),
              tl: {
                hd: Curry._2(Internal__Dust_Syntax$Dust.Html.Elements.body, {
                      hd: Curry._1(Internal__Dust_Syntax$Dust.Html.Properties.class_, "bg-black"),
                      tl: /* [] */0
                    }, {
                      hd: Curry._2(Internal__Dust_Syntax$Dust.Html.Elements.h1, {
                            hd: Curry._1(Internal__Dust_Syntax$Dust.Html.Properties.class_, "mx-auto text-center text-red-500 font-bold text-6xl"),
                            tl: /* [] */0
                          }, Curry._1(Internal__Dust_Syntax$Dust.Html.Elements.text, "Coming soon")),
                      tl: {
                        hd: Curry._2(Internal__Dust_Syntax$Dust.Html.Elements.div, /* [] */0, {
                              hd: post.content,
                              tl: /* [] */0
                            }),
                        tl: /* [] */0
                      }
                    }),
                tl: /* [] */0
              }
            });
}

var H;

var P;

exports.H = H;
exports.P = P;
exports.main = main;
/* No side effect */
